//
//  BalletMoves.swift
//  AniDraw
//
//  Created by Mike on 7/15/16.
//  Copyright © 2016 yanjingzz. All rights reserved.
//

import Foundation

struct BalletMoves {
    static func createAll() {
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.76303,
                            .LeftShank: 0.0,
                            .RightFoot: -1.1486,
                            .LeftThigh: 0.0268462,
                            .LowerBody: 0.0192984,
                            .RightShank: 0.0,
                            .Head: -0.179911,
                            .RightForearm: 0.943188,
                            .LeftFoot: 1.00062,
                            .RightUpperArm: 2.65677,
                            .UpperBody: -0.133945,
                            .RightThigh: 0.396764,
                            .LeftForearm: 5.47937],
                        position: CGPoint(x: -35.0, y: 103.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.24923,
                            .LeftShank: 0.0,
                            .RightFoot: -1.18648,
                            .LeftThigh: -1.34466,
                            .LowerBody: -0.167947,
                            .RightShank: 0.0,
                            .Head: -0.142206,
                            .RightForearm: 0.813024,
                            .LeftFoot: 0.953312,
                            .RightUpperArm: 2.63408,
                            .UpperBody: 0.0675662,
                            .RightThigh: 0.168127,
                            .LeftForearm: 5.75816],
                        position: CGPoint(x: -48.0, y: 44.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.58718,
                            .LeftShank: 0.0,
                            .RightFoot: -1.1486,
                            .LeftThigh: -0.554489,
                            .LowerBody: 0.0441935,
                            .RightShank: 0.0,
                            .Head: 0.046351,
                            .RightForearm: 0.944984,
                            .LeftFoot: 1.00062,
                            .RightUpperArm: 2.61741,
                            .UpperBody: -0.0782712,
                            .RightThigh: 0.555199,
                            .LeftForearm: 5.61928],
                        position: CGPoint(x: -149.5, y: 94.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.55868,
                            .LeftShank: 0.99774,
                            .RightFoot: -1.39337,
                            .LeftThigh: -0.900572,
                            .LowerBody: 0.321268,
                            .RightShank: 0.0,
                            .Head: 0.0715435,
                            .RightForearm: 0.895428,
                            .LeftFoot: -0.416411,
                            .RightUpperArm: 2.62797,
                            .UpperBody: -0.0176973,
                            .RightThigh: 1.23421,
                            .LeftForearm: 5.55977],
                        position: CGPoint(x: -202.0, y: 18.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut)],
            levelOfIntensity: 2,
            style: .Ballet,
            name: "Small Hop walk")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.38713,
                            .LeftShank: 0.0,
                            .RightFoot: -0.761382,
                            .LeftThigh: -0.0712495,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 1.10135,
                            .LeftFoot: 0.604356, 
                            .RightUpperArm: 2.57676, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.128207, 
                            .LeftForearm: 5.8254], 
                        position: CGPoint(x: -3.0, y: 38.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.38713, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.456786, 
                            .LeftThigh: 0.211088, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 1.10135, 
                            .LeftFoot: -0.181931, 
                            .RightUpperArm: 2.57676, 
                            .UpperBody: 0.0, 
                            .RightThigh: -0.259116, 
                            .LeftForearm: 5.8254], 
                        position: CGPoint(x: -2.5, y: 9.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.38713, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.00579, 
                            .LeftThigh: -0.0991131, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 1.10135, 
                            .LeftFoot: 0.975606, 
                            .RightUpperArm: 2.57676, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.127536, 
                            .LeftForearm: 5.8254], 
                        position: CGPoint(x: -9.0, y: 42.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.38713, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.308271, 
                            .LeftThigh: 0.171394, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 1.10135, 
                            .LeftFoot: -0.268514, 
                            .RightUpperArm: 2.57676, 
                            .UpperBody: 0.0, 
                            .RightThigh: -0.22556, 
                            .LeftForearm: 5.8254], 
                        position: CGPoint(x: -4.5, y: 14.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn)], 
            levelOfIntensity: 1, 
            style: .Ballet,
            name: "Ballet Shuffle")
        
        _ = DanceMove( 
            keyframes:
            [
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.38713, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.761382, 
                            .LeftThigh: -0.0712495, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 1.10135, 
                            .LeftFoot: 0.913119, 
                            .RightUpperArm: 2.57676, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.128207, 
                            .LeftForearm: 5.8254], 
                        position: CGPoint(x: -3.0, y: 38.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.38713, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.456786, 
                            .LeftThigh: 0.211088, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 1.10135, 
                            .LeftFoot: -0.181931, 
                            .RightUpperArm: 2.57676, 
                            .UpperBody: 0.0, 
                            .RightThigh: -0.259116, 
                            .LeftForearm: 5.8254], 
                        position: CGPoint(x: -2.5, y: 9.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.38713, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.00579, 
                            .LeftThigh: 0.0347005, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 1.10135, 
                            .LeftFoot: 0.975606, 
                            .RightUpperArm: 2.57676, 
                            .UpperBody: 0.0, 
                            .RightThigh: -0.105939, 
                            .LeftForearm: 5.8254], 
                        position: CGPoint(x: -10.0, y: 88.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.38713, 
                            .LeftShank: 1.95699, 
                            .RightFoot: 0.308271, 
                            .LeftThigh: -0.489937, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 1.10135, 
                            .LeftFoot: -5.17585, 
                            .RightUpperArm: 2.57676, 
                            .UpperBody: 0.0, 
                            .RightThigh: -0.22556, 
                            .LeftForearm: 5.8254], 
                        position: CGPoint(x: -4.5, y: 14.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn)], 
            levelOfIntensity: 2,
            style: .Ballet,
            name: "Ballet Shuffle And Hop")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.396707,
                            .LeftShank: 0.0,
                            .RightFoot: -1.1486,
                            .LeftThigh: 0.0268462,
                            .LowerBody: 0.0192984,
                            .RightShank: 0.0,
                            .Head: -0.179911,
                            .RightForearm: 5.61691,
                            .LeftFoot: 1.00062,
                            .RightUpperArm: -0.245402,
                            .UpperBody: -0.133945,
                            .RightThigh: 0.396764,
                            .LeftForearm: 0.65947],
                        position: CGPoint(x: -35.0, y: 103.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.786619,
                            .LeftShank: 0.0,
                            .RightFoot: -1.18648,
                            .LeftThigh: -0.472314,
                            .LowerBody: -0.167947,
                            .RightShank: 0.0,
                            .Head: -0.142206,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.990932,
                            .RightUpperArm: -0.699925,
                            .UpperBody: 0.0675662,
                            .RightThigh: 0.126692,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -48.0, y: 44.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.443391,
                            .LeftShank: 0.0,
                            .RightFoot: -1.18648,
                            .LeftThigh: 0.0533416,
                            .LowerBody: -0.167947,
                            .RightShank: 0.0,
                            .Head: -0.142206,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.990932,
                            .RightUpperArm: 0.421421,
                            .UpperBody: 0.0675662,
                            .RightThigh: 0.126692,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -47.0, y: 97.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 2.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.03604,
                            .LeftShank: 0.0,
                            .RightFoot: -0.752029,
                            .LeftThigh: -0.452013,
                            .LowerBody: -0.154467,
                            .RightShank: 0.0,
                            .Head: -0.431372,
                            .RightForearm: 0.684998,
                            .LeftFoot: 1.06314,
                            .RightUpperArm: 1.05447,
                            .UpperBody: 0.517393,
                            .RightThigh: 1.54187,
                            .LeftForearm: 5.7828],
                        position: CGPoint(x: -75.0, y: 45.5)),
                    angleCurve: .ExponentialEaseOut,
                    positionCurve: .ExponentialEaseOut)],
            levelOfIntensity: 4,
            style: .Ballet,
            name: "Ballet Side Stretch")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.27713,
                            .LeftShank: 2.25062,
                            .RightFoot: -0.7607,
                            .LeftThigh: -1.33886,
                            .LowerBody: 0.0192285,
                            .RightShank: 0.0,
                            .Head: -0.182564,
                            .RightForearm: 3.54974,
                            .LeftFoot: 0.786633,
                            .RightUpperArm: 1.1353,
                            .UpperBody: -0.0192285,
                            .RightThigh: 0.0,
                            .LeftForearm: 3.14159],
                        position: CGPoint(x: 46.0, y: 15.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.393092,
                            .LeftShank: 0.616803,
                            .RightFoot: -5.69675,
                            .LeftThigh: -0.292811,
                            .LowerBody: 0.0192285,
                            .RightShank: 5.62491,
                            .Head: 0.043135,
                            .RightForearm: 5.23016,
                            .LeftFoot: 0.786633,
                            .RightUpperArm: 0.396727,
                            .UpperBody: -0.0192285,
                            .RightThigh: 0.242091,
                            .LeftForearm: 1.0751],
                        position: CGPoint(x: 13.0, y: -13.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.41794,
                            .LeftShank: 2.31191,
                            .RightFoot: -0.726013,
                            .LeftThigh: -1.17253,
                            .LowerBody: 0.0192285,
                            .RightShank: 0.0,
                            .Head: 0.043135,
                            .RightForearm: 2.88216,
                            .LeftFoot: 0.786633,
                            .RightUpperArm: 1.52528,
                            .UpperBody: -0.0192285,
                            .RightThigh: 0.0283166,
                            .LeftForearm: 3.14159],
                        position: CGPoint(x: 53.0, y: 20.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.428237,
                            .LeftShank: 0.990386,
                            .RightFoot: -5.567,
                            .LeftThigh: -0.440264,
                            .LowerBody: -0.0756131,
                            .RightShank: 5.26947,
                            .Head: 0.0,
                            .RightForearm: 5.19595,
                            .LeftFoot: 0.780424,
                            .RightUpperArm: 0.474285,
                            .UpperBody: 0.0,
                            .RightThigh: 0.470906,
                            .LeftForearm: 1.16362],
                        position: CGPoint(x: 21.0, y: -13.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.48035,
                            .LeftShank: 0.0,
                            .RightFoot: -1.03653,
                            .LeftThigh: -1.36068,
                            .LowerBody: -0.0756131,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.550482,
                            .LeftFoot: 0.780424,
                            .RightUpperArm: 1.40938,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0941575,
                            .LeftForearm: 5.36837],
                        position: CGPoint(x: 79.5, y: 27.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut)],
            levelOfIntensity: 3,
            style: .Ballet,
            name: "Ballet Pose And Kick")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.17307,
                            .LeftShank: 0.0,
                            .RightFoot: -0.858693,
                            .LeftThigh: 0.210055,
                            .LowerBody: -0.152649,
                            .RightShank: 5.29282,
                            .Head: 0.0,
                            .RightForearm: 3.71027,
                            .LeftFoot: 0.90551,
                            .RightUpperArm: 1.34381,
                            .UpperBody: 0.0,
                            .RightThigh: 0.221939,
                            .LeftForearm: 2.74976],
                        position: CGPoint(x: -42.0, y: 14.5)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.46394,
                            .LeftShank: 1.57154,
                            .RightFoot: -1.01089,
                            .LeftThigh: -0.859598,
                            .LowerBody: -0.438859,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 3.61078,
                            .LeftFoot: 0.90551,
                            .RightUpperArm: 1.28247,
                            .UpperBody: 0.0,
                            .RightThigh: 0.11398,
                            .LeftForearm: 2.6608],
                        position: CGPoint(x: 15.5, y: 24.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.480726,
                            .LeftShank: 0.0,
                            .RightFoot: -0.662236,
                            .LeftThigh: 4.91243,
                            .LowerBody: -0.210183,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 5.44672,
                            .LeftFoot: 0.664838,
                            .RightUpperArm: 0.152368,
                            .UpperBody: 0.0,
                            .RightThigh: 0.176876,
                            .LeftForearm: 1.52143],
                        position: CGPoint(x: -34.5, y: 46.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.78234,
                            .LeftShank: 0.0,
                            .RightFoot: -0.662236,
                            .LeftThigh: 4.91243,
                            .LowerBody: 0.116236,
                            .RightShank: 0.0,
                            .Head: 0.0653586,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.664838,
                            .RightUpperArm: 1.64833,
                            .UpperBody: -0.19502,
                            .RightThigh: 1.37559,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -338.0, y: 126.0)),
                    angleCurve: .Linear,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.25449,
                            .LeftShank: 0.0,
                            .RightFoot: -0.662236,
                            .LeftThigh: 0.0820597,
                            .LowerBody: -0.0485448,
                            .RightShank: 0.0,
                            .Head: 0.0173415,
                            .RightForearm: 1.13788,
                            .LeftFoot: 0.664838,
                            .RightUpperArm: 2.50529,
                            .UpperBody: 0.0,
                            .RightThigh: 1.37559,
                            .LeftForearm: 5.44053],
                        position: CGPoint(x: -512.5, y: 9.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut)],
            levelOfIntensity: 5,
            style: .Ballet,
            name: "Ballet Big Hop")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.18564,
                            .LeftShank: 0.895462,
                            .RightFoot: -0.930421,
                            .LeftThigh: -0.722801,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 3.68177,
                            .LeftFoot: 1.10147,
                            .RightUpperArm: 1.4215,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0,
                            .LeftForearm: 2.95063],
                        position: CGPoint(x: 29.0, y: 18.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.22007, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.715269, 
                            .LeftThigh: -0.89394, 
                            .LowerBody: -0.25681, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 2.98525, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 2.12755, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.275897, 
                            .LeftForearm: 3.59802], 
                        position: CGPoint(x: 44.0, y: 16.5)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.42134, 
                            .LeftShank: 0.804266, 
                            .RightFoot: -0.980205, 
                            .LeftThigh: -0.727947, 
                            .LowerBody: 0.0286685, 
                            .RightShank: 6.07681, 
                            .Head: 0.0, 
                            .RightForearm: 2.77341, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 1.49624, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.0589119, 
                            .LeftForearm: 5.56081], 
                        position: CGPoint(x: 38.0, y: 12.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.40085, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.700063, 
                            .LeftThigh: -0.419383, 
                            .LowerBody: 0.385771, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.857233, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 1.30967, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.171193, 
                            .LeftForearm: 5.335], 
                        position: CGPoint(x: -66.0, y: 27.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.28715, 
                            .LeftShank: 0.551602, 
                            .RightFoot: -0.700063, 
                            .LeftThigh: -0.297729, 
                            .LowerBody: 0.070725, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.714641, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 1.46034, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: -0.138925, 
                            .LeftForearm: 5.95888], 
                        position: CGPoint(x: -94.5, y: 16.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.24718, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.38791, 
                            .LeftThigh: -0.538134, 
                            .LowerBody: -0.394238, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.531258, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 1.59713, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.509845, 
                            .LeftForearm: 5.66576], 
                        position: CGPoint(x: -99.0, y: 21.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.76474, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.700063, 
                            .LeftThigh: -0.552871, 
                            .LowerBody: 0.110983, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.653624, 
                            .LeftFoot: 0.729238, 
                            .RightUpperArm: 1.6088, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.305346, 
                            .LeftForearm: 5.00223], 
                        position: CGPoint(x: -206.5, y: 95.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.3609, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.700063, 
                            .LeftThigh: -0.419383, 
                            .LowerBody: 0.385771, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.566888, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 1.21821, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.646172, 
                            .LeftForearm: 5.22429], 
                        position: CGPoint(x: -241.5, y: 29.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.47253, 
                            .LeftShank: 0.83786, 
                            .RightFoot: -0.700063, 
                            .LeftThigh: -0.393059, 
                            .LowerBody: 0.0204198, 
                            .RightShank: 5.33783, 
                            .Head: 0.0, 
                            .RightForearm: 1.10654, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 1.44123, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.416679, 
                            .LeftForearm: 5.73412], 
                        position: CGPoint(x: -194.5, y: 13.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.46876, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.30533, 
                            .LeftThigh: -0.419383, 
                            .LowerBody: -0.253024, 
                            .RightShank: 5.94162, 
                            .Head: 0.0, 
                            .RightForearm: 0.657676, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 1.41563, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.599031, 
                            .LeftForearm: 5.64126], 
                        position: CGPoint(x: -200.5, y: 22.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.3609, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.700063, 
                            .LeftThigh: -0.419383, 
                            .LowerBody: 0.0814354, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.566888, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 1.21821, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.646172, 
                            .LeftForearm: 5.22429], 
                        position: CGPoint(x: -278.0, y: 68.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.90033, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.700063, 
                            .LeftThigh: -0.419383, 
                            .LowerBody: 0.385771, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.566888, 
                            .LeftFoot: 1.00048, 
                            .RightUpperArm: 1.21821, 
                            .UpperBody: -0.0444152, 
                            .RightThigh: 0.646172, 
                            .LeftForearm: 5.44686], 
                        position: CGPoint(x: -388.5, y: 29.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut)], 
            levelOfIntensity: 3,
            style: .Ballet,
            name: "Walk And Hop")
        
        _ = DanceMove( 
            keyframes:
            [
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -0.380756, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.820531, 
                            .LeftThigh: 0.0, 
                            .LowerBody: 0.0, 
                            .RightShank: 4.2815, 
                            .Head: 0.0, 
                            .RightForearm: 4.82474, 
                            .LeftFoot: 0.922988, 
                            .RightUpperArm: 0.0659097, 
                            .UpperBody: 0.0, 
                            .RightThigh: 1.00762, 
                            .LeftForearm: 2.06599], 
                        position: CGPoint(x: -18.5, y: 33.5)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut), 
                Keyframe( 
                    time: 2.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.90042, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.03024, 
                            .LeftThigh: -0.547352, 
                            .LowerBody: 0.224993, 
                            .RightShank: 0.0, 
                            .Head: -0.29962, 
                            .RightForearm: 0.756677, 
                            .LeftFoot: 0.948858, 
                            .RightUpperArm: 1.1534, 
                            .UpperBody: 0.356912, 
                            .RightThigh: 1.62741, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -76.0, y: 24.0)), 
                    angleCurve: .ExponentialEaseOut, 
                    positionCurve: .ExponentialEaseOut)], 
            levelOfIntensity: 4,
            style: .Ballet,
            name: "Stretch")
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.345304,
                            .LeftShank: 0.895603,
                            .RightFoot: -1.05963,
                            .LeftThigh: -0.585684,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 5.60823,
                            .LeftFoot: 1.21295,
                            .RightUpperArm: 0.258968,
                            .UpperBody: 0.0,
                            .RightThigh: -0.0720985,
                            .LeftForearm: 0.749086],
                        position: CGPoint(x: 45.5, y: 9.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.576555,
                            .LeftShank: 0.0,
                            .RightFoot: -1.05963,
                            .LeftThigh: -0.187316,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 4.68216,
                            .LeftFoot: 1.21295,
                            .RightUpperArm: 0.661193,
                            .UpperBody: 0.0,
                            .RightThigh: 0.137664,
                            .LeftForearm: 1.78258],
                        position: CGPoint(x: 11.0, y: 6.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.15028,
                            .LeftShank: 0.0,
                            .RightFoot: -0.627627,
                            .LeftThigh: -0.108631,
                            .LowerBody: 0.0,
                            .RightShank: 4.70417,
                            .Head: 0.0,
                            .RightForearm: 3.90982,
                            .LeftFoot: 1.21295,
                            .RightUpperArm: 1.12887,
                            .UpperBody: 0.0,
                            .RightThigh: 0.849464,
                            .LeftForearm: 2.19255],
                        position: CGPoint(x: -17.0, y: 12.0)),
                    angleCurve: .Linear,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.62329,
                            .LeftShank: 0.0,
                            .RightFoot: -0.627627,
                            .LeftThigh: -0.176931,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 2.80774,
                            .LeftFoot: 0.869329,
                            .RightUpperArm: 1.60398,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0140178,
                            .LeftForearm: 3.61242],
                        position: CGPoint(x: 6.0, y: 15.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.51724,
                            .LeftShank: 0.895603,
                            .RightFoot: -1.05963,
                            .LeftThigh: -0.585684,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 2.93854,
                            .LeftFoot: 1.21295,
                            .RightUpperArm: 1.67603,
                            .UpperBody: 0.0,
                            .RightThigh: -0.0720985,
                            .LeftForearm: 3.26787],
                        position: CGPoint(x: 45.5, y: 9.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.47266,
                            .LeftShank: 0.0,
                            .RightFoot: -1.05963,
                            .LeftThigh: -0.187316,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 2.52701,
                            .LeftFoot: 1.21295,
                            .RightUpperArm: 2.05237,
                            .UpperBody: 0.0,
                            .RightThigh: 0.137664,
                            .LeftForearm: 3.6731],
                        position: CGPoint(x: 11.0, y: 6.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.94509,
                            .LeftShank: 0.0,
                            .RightFoot: -0.627627,
                            .LeftThigh: -0.108631,
                            .LowerBody: 0.0,
                            .RightShank: 4.70417,
                            .Head: 0.0,
                            .RightForearm: 1.79484,
                            .LeftFoot: 1.21295,
                            .RightUpperArm: 2.18078,
                            .UpperBody: 0.0,
                            .RightThigh: 0.849464,
                            .LeftForearm: 4.7384],
                        position: CGPoint(x: -17.0, y: 12.0)),
                    angleCurve: .Linear,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.2459,
                            .LeftShank: 0.0,
                            .RightFoot: -0.627627,
                            .LeftThigh: -0.176931,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.59009,
                            .LeftFoot: 0.869329,
                            .RightUpperArm: 2.88101,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0140178,
                            .LeftForearm: 5.69559],
                        position: CGPoint(x: 6.0, y: 15.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear)],
            levelOfIntensity: 2,
            style: .Ballet,
            name: "Quick Steps")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.97423,
                            .LeftShank: 0.0,
                            .RightFoot: -0.945122,
                            .LeftThigh: -0.308376,
                            .LowerBody: -0.021294,
                            .RightShank: 0.0,
                            .Head: 0.0974797,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.656701,
                            .RightUpperArm: -1.24446,
                            .UpperBody: 0.15595,
                            .RightThigh: 0.0436575,
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -32.8857, y: 31.8723)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.75, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 1.73968, 
                            .LeftShank: 1.98903, 
                            .RightFoot: -0.841142, 
                            .LeftThigh: -0.863789, 
                            .LowerBody: 0.166036, 
                            .RightShank: 0.0, 
                            .Head: -0.00667751, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.79729, 
                            .RightUpperArm: 1.43212, 
                            .UpperBody: -0.871604, 
                            .RightThigh: 0.709391, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 50.0, y: 38.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 5.17036, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.842378, 
                            .LeftThigh: -1.40965, 
                            .LowerBody: -0.336514, 
                            .RightShank: 0.0, 
                            .Head: -0.00834692, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.772243, 
                            .RightUpperArm: 2.53879, 
                            .UpperBody: 0.0144103, 
                            .RightThigh: 0.314909, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 41.1143, y: 42.3723)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut)], 
            levelOfIntensity: 4,
            style: .Ballet,
            name: "Side Slide And Lift")
        
        _ = DanceMove( 
            keyframes:
            [
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.00869, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.04853, 
                            .LeftThigh: -0.31074, 
                            .LowerBody: -0.505285, 
                            .RightShank: 0.0, 
                            .Head: -0.608697, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.717573, 
                            .RightUpperArm: 2.60263, 
                            .UpperBody: 0.819283, 
                            .RightThigh: 1.98101, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -53.0, y: 31.0)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -1.48754, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.977011, 
                            .LeftThigh: -0.379437, 
                            .LowerBody: 0.400103, 
                            .RightShank: 0.0, 
                            .Head: 0.0424993, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.717573, 
                            .RightUpperArm: 0.744297, 
                            .UpperBody: -0.247454, 
                            .RightThigh: -0.0825132, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -4.5, y: 23.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.75, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 5.30193, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.842332, 
                            .LeftThigh: -1.37788, 
                            .LowerBody: 6.24902, 
                            .RightShank: 0.0, 
                            .Head: 0.191457, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.921391, 
                            .RightUpperArm: 2.0583, 
                            .UpperBody: -1.87592, 
                            .RightThigh: -4.33473, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 119.5, y: -77.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 5.30193, 
                            .LeftShank: 1.54982, 
                            .RightFoot: -0.820717, 
                            .LeftThigh: -0.389659, 
                            .LowerBody: -0.108704, 
                            .RightShank: 0.0, 
                            .Head: 0.0117745, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.966278, 
                            .RightUpperArm: 0.662649, 
                            .UpperBody: -0.71465, 
                            .RightThigh: 0.786815, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 105.5, y: 2.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 5.69831, 
                            .LeftShank: 0.00267446, 
                            .RightFoot: -0.906331, 
                            .LeftThigh: -0.113877, 
                            .LowerBody: -0.0339541, 
                            .RightShank: 0.0, 
                            .Head: -0.00190135, 
                            .RightForearm: -0.583607, 
                            .LeftFoot: 0.966278, 
                            .RightUpperArm: 0.403364, 
                            .UpperBody: 0.0699511, 
                            .RightThigh: 0.00145823, 
                            .LeftForearm: 0.57673], 
                        position: CGPoint(x: 11.5621, y: 6.00381)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut)], 
            levelOfIntensity: 5,
            style: .Ballet,
            name: "Small And Big Kicks")

        
        _ = DanceMove( 
            keyframes:
            [
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.76303, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.1486, 
                            .LeftThigh: 0.0268462, 
                            .LowerBody: 0.0192984, 
                            .RightShank: 0.0, 
                            .Head: -0.179911, 
                            .RightForearm: 0.943188, 
                            .LeftFoot: 1.00062, 
                            .RightUpperArm: 2.65677, 
                            .UpperBody: -0.133945, 
                            .RightThigh: 0.396764, 
                            .LeftForearm: 5.47937], 
                        position: CGPoint(x: -35.0, y: 103.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.24923, 
                            .LeftShank: 0.765859, 
                            .RightFoot: -1.1486, 
                            .LeftThigh: -0.136561, 
                            .LowerBody: -0.167947, 
                            .RightShank: 5.0648, 
                            .Head: -0.142206, 
                            .RightForearm: 0.813024, 
                            .LeftFoot: 1.02019, 
                            .RightUpperArm: 2.63408, 
                            .UpperBody: 0.0675662, 
                            .RightThigh: -0.187116, 
                            .LeftForearm: 5.75816], 
                        position: CGPoint(x: -30.0, y: 2.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.58718, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.1486, 
                            .LeftThigh: 0.0141237, 
                            .LowerBody: -0.0102069, 
                            .RightShank: 0.0, 
                            .Head: -0.142206, 
                            .RightForearm: 0.944984, 
                            .LeftFoot: 1.00062, 
                            .RightUpperArm: 2.61741, 
                            .UpperBody: -0.0782712, 
                            .RightThigh: 0.201266, 
                            .LeftForearm: 5.61928], 
                        position: CGPoint(x: -74.0, y: 103.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.55868, 
                            .LeftShank: 1.32029, 
                            .RightFoot: -1.27152, 
                            .LeftThigh: 0.00507209, 
                            .LowerBody: 0.141204, 
                            .RightShank: 5.51511, 
                            .Head: -0.142206, 
                            .RightForearm: 0.895428, 
                            .LeftFoot: 1.00062, 
                            .RightUpperArm: 2.62797, 
                            .UpperBody: -0.0176973, 
                            .RightThigh: 0.144191, 
                            .LeftForearm: 5.55977], 
                        position: CGPoint(x: -81.0, y: -4.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut)], 
            levelOfIntensity: 3,
            style: .Ballet,
            name: "Cross walk")
    }

}