//
//  GenericMoves.swift
//  AniDraw
//
//  Created by Mike on 7/15/16.
//  Copyright © 2016 yanjingzz. All rights reserved.
//

import Foundation

class GenericMoves {
    static func createAll() {
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.212434,
                            .LeftShank: 0.0,
                            .RightFoot: -5.86675,
                            .RightShank: 5.21679,
                            .LowerBody: 0.0,
                            .LeftThigh: -0.0317614,
                            .Head: 0.0,
                            .RightForearm: 0.404496,
                            .LeftFoot: 0.0468583,
                            .RightUpperArm: 1.74027,
                            .UpperBody: 0.0,
                            .RightThigh: 0.738138,
                            .LeftForearm: 1.08414],
                        position: CGPoint(x: 14.0, y: -2.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.581887,
                            .LeftShank: 1.03669,
                            .RightFoot: -5.75075,
                            .RightShank: 5.23488,
                            .LowerBody: 0.0,
                            .LeftThigh: -0.664357,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.45891,
                            .RightUpperArm: 0.511078,
                            .UpperBody: 0.0,
                            .RightThigh: 0.452114,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 32.5, y: -23.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.28505,
                            .LeftShank: 1.03669,
                            .RightFoot: -0.0858394,
                            .RightShank: 0.0,
                            .LowerBody: 0.0,
                            .LeftThigh: -0.664357,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.45891,
                            .RightUpperArm: -1.22458,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0443267,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 14.0, y: 0.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.0924009,
                            .LeftShank: 1.03669,
                            .RightFoot: -5.60078,
                            .RightShank: 5.2574,
                            .LowerBody: 0.0,
                            .LeftThigh: -0.664357,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.45891,
                            .RightUpperArm: 0.458119,
                            .UpperBody: 0.0,
                            .RightThigh: 0.410125,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 45.0, y: -16.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.916206,
                            .LeftShank: 0.0,
                            .RightFoot: -0.0858394,
                            .RightShank: 5.01224,
                            .LowerBody: 0.0,
                            .LeftThigh: -0.0628535,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.0571009,
                            .RightUpperArm: 2.15993,
                            .UpperBody: 0.0,
                            .RightThigh: 1.30514,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 14.0, y: 0.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.32004,
                            .LeftShank: 0.00221302,
                            .RightFoot: 0.00212226,
                            .RightShank: 6.27714,
                            .LowerBody: 0.0,
                            .LeftThigh: -0.0244834,
                            .Head: 0.0,
                            .RightForearm: 0.400002,
                            .LeftFoot: -0.0376401,
                            .RightUpperArm: 1.71617,
                            .UpperBody: 0.0,
                            .RightThigh: -0.00380611,
                            .LeftForearm: 0.000216067],
                        position: CGPoint(x: 11.0601, y: 2.94208)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut)],
            levelOfIntensity: 1,
            name: "Steps")
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.0844275,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: 0.0120476,
                            .LeftThigh: 0.0,
                            .Head: -0.159996,
                            .RightForearm: 2.31705,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.122035,
                            .UpperBody: -0.0120476,
                            .RightThigh: 0.0,
                            .LeftForearm: 2.52311],
                        position: CGPoint(x: 0.0, y: 0.0)),
                    angleCurve: .SineEaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.0352426,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: -0.108271,
                            .LeftThigh: 0.0,
                            .Head: 0.348284,
                            .RightForearm: 4.45608,
                            .LeftFoot: 0.0,
                            .RightUpperArm: -0.478076,
                            .UpperBody: 0.108271,
                            .RightThigh: 0.0,
                            .LeftForearm: 4.12286],
                        position: CGPoint(x: 0.0, y: 0.0)),
                    angleCurve: .SineEaseInOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.240673,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: -0.012345,
                            .LeftThigh: 0.0,
                            .Head: -0.199046,
                            .RightForearm: 1.94886,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.611888,
                            .UpperBody: 0.012345,
                            .RightThigh: 0.0,
                            .LeftForearm: 2.16721],
                        position: CGPoint(x: 0.0, y: 0.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.00179362,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: 0.00047636,
                            .LeftThigh: 0.0,
                            .Head: 0.000266448,
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.00151187, 
                            .UpperBody: -0.00047636, 
                            .RightThigh: 0.0, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0, y: 0.0)), 
                    angleCurve: .SineEaseInOut, 
                    positionCurve: .EaseIn)], 
            levelOfIntensity: 1,
            name: "Shake head")
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 2.07887, 
                            .LeftShank: 0.602443, 
                            .RightFoot: 0.129851, 
                            .RightShank: 5.42809, 
                            .LowerBody: 0.0, 
                            .LeftThigh: -0.388878, 
                            .Head: 0.0, 
                            .RightForearm: 1.24402, 
                            .LeftFoot: -0.248976, 
                            .RightUpperArm: 1.54063, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.391459, 
                            .LeftForearm: 1.065], 
                        position: CGPoint(x: 12.0, y: -16.5)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 2.17019, 
                            .LeftShank: 0.0, 
                            .RightFoot: -5.94116, 
                            .RightShank: 0.0, 
                            .LowerBody: 0.0, 
                            .LeftThigh: 0.00724173, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.248976, 
                            .RightUpperArm: 1.84369, 
                            .UpperBody: 0.0, 
                            .RightThigh: -0.109601, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -1.5, y: -7.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -0.192614, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.129851, 
                            .RightShank: 0.0, 
                            .LowerBody: 0.0, 
                            .LeftThigh: -0.00815463, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.248976, 
                            .RightUpperArm: 0.20631, 
                            .UpperBody: 0.0, 
                            .RightThigh: -0.00120103, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -6.0, y: -13.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.75452, 
                            .LeftShank: 0.85329, 
                            .RightFoot: 0.129851, 
                            .RightShank: 5.91768, 
                            .LowerBody: 0.0, 
                            .LeftThigh: -0.593348, 
                            .Head: 0.0, 
                            .RightForearm: 4.22848, 
                            .LeftFoot: -0.248976, 
                            .RightUpperArm: 5.64553, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.260791, 
                            .LeftForearm: 4.85075], 
                        position: CGPoint(x: -22.0, y: -11.0)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.358, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.129851, 
                            .RightShank: 0.0, 
                            .LowerBody: -0.00552475, 
                            .LeftThigh: -0.0818013, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.248976, 
                            .RightUpperArm: -1.35173, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.0375671, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -6.0, y: -12.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 6.27853, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.000313774, 
                            .RightShank: 0.0, 
                            .LowerBody: -1.33496e-05, 
                            .LeftThigh: -0.000197679, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.000601605, 
                            .RightUpperArm: -0.00326622, 
                            .UpperBody: 0.0, 
                            .RightThigh: 9.07779e-05, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0032959, y: -0.0535889)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut)], 
            levelOfIntensity: 2,
            name: "Cheer wave")
        
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.38907,
                            .LeftShank: 1.08041,
                            .RightFoot: -5.74324,
                            .RightShank: 5.3312,
                            .LowerBody: -0.135528,
                            .LeftThigh: -0.59127,
                            .Head: 0.0,
                            .RightForearm: 5.47277,
                            .LeftFoot: -0.506261,
                            .RightUpperArm: 1.06802,
                            .UpperBody: 0.135528,
                            .RightThigh: 0.548701,
                            .LeftForearm: 0.767658],
                        position: CGPoint(x: 3.0, y: -37.5)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.316026,
                            .LeftShank: 0.00233781,
                            .RightFoot: -6.62952,
                            .RightShank: 6.28113,
                            .LowerBody: -0.222598,
                            .LeftThigh: -0.00127935,
                            .Head: -0.0373335,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.46182,
                            .RightUpperArm: 0.307634,
                            .UpperBody: 0.222598,
                            .RightThigh: 0.00118726,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 7.00647, y: 328.919)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.24605,
                            .LeftShank: 1.19323,
                            .RightFoot: -6.01308,
                            .RightShank: 5.03207,
                            .LowerBody: 0.135007,
                            .LeftThigh: -0.579639,
                            .Head: -0.318324,
                            .RightForearm: 5.25898,
                            .LeftFoot: -0.691765,
                            .RightUpperArm: 1.30284,
                            .UpperBody: -0.077768,
                            .RightThigh: 0.770994,
                            .LeftForearm: 0.713748],
                        position: CGPoint(x: 2.00647, y: -37.0811)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.00528872,
                            .LeftShank: 0.00506449,
                            .RightFoot: -6.28204,
                            .RightShank: 6.27787,
                            .LowerBody: 0.000573024,
                            .LeftThigh: -0.00246018,
                            .Head: -0.00135106,
                            .RightForearm: 6.27884,
                            .LeftFoot: -0.00293607,
                            .RightUpperArm: 0.00552964,
                            .UpperBody: -0.000330068,
                            .RightThigh: 0.00327235,
                            .LeftForearm: 0.00302941],
                        position: CGPoint(x: 0.00854492, y: -0.157379)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut)],
            levelOfIntensity: 3,
            name: "Big jump")
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.926372,
                            .LeftShank: 1.10394,
                            .RightFoot: -5.76585,
                            .RightShank: 5.12722,
                            .LowerBody: -0.180799,
                            .LeftThigh: -0.771706,
                            .Head: 0.0754184,
                            .RightForearm: 5.74003,
                            .LeftFoot: -0.235035,
                            .RightUpperArm: 0.672806,
                            .UpperBody: 0.180799,
                            .RightThigh: 0.626103,
                            .LeftForearm: 0.630767],
                        position: CGPoint(x: 2.0, y: -41.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.208478,
                            .LeftShank: 0.22306,
                            .RightFoot: -5.86058,
                            .RightShank: 0.0,
                            .LowerBody: 0.116567,
                            .LeftThigh: -0.186969,
                            .Head: 0.0754184,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.514373,
                            .RightUpperArm: -0.215871,
                            .UpperBody: -0.0739391,
                            .RightThigh: 0.00597715,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -3.5, y: 63.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.86488,
                            .LeftShank: 1.38057,
                            .RightFoot: -0.555022,
                            .RightShank: 5.3255,
                            .LowerBody: 0.213831,
                            .LeftThigh: -1.22625,
                            .Head: -0.0431839,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.514373,
                            .RightUpperArm: 0.411276,
                            .UpperBody: 0.209023,
                            .RightThigh: 0.422313,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 5.0, y: -54.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.495867758989334,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.86522,
                            .LeftShank: 1.38057,
                            .RightFoot: -0.575862,
                            .RightShank: 0.0,
                            .LowerBody: 0.213831,
                            .LeftThigh: -1.22625,
                            .Head: -0.0431839,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.514373,
                            .RightUpperArm: 1.67163,
                            .UpperBody: 0.209023,
                            .RightThigh: 1.29189,
                            .LeftForearm: 5.48836],
                        position: CGPoint(x: 5.0, y: -54.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 5.81999,
                            .LeftShank: 0.00175166,
                            .RightFoot: 0.192663,
                            .RightShank: 6.2818,
                            .LowerBody: -0.00486511,
                            .LeftThigh: -0.0223852,
                            .Head: 0.016594,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.286297,
                            .RightUpperArm: 0.240143,
                            .UpperBody: 0.0524767,
                            .RightThigh: -0.0236341,
                            .LeftForearm: 6.28218],
                        position: CGPoint(x: 0.505737, y: -21.0425)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut)],
            levelOfIntensity: 3,
            name: "Jump & side kick")
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.575708,
                            .LeftShank: 1.24168,
                            .RightFoot: -0.0100373,
                            .RightShank: 5.01544,
                            .LowerBody: 0.0139512,
                            .LeftThigh: -0.869606,
                            .Head: 0.120338,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.0706744,
                            .RightUpperArm: 0.39693,
                            .UpperBody: 0.0861498,
                            .RightThigh: 0.693709,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 2.5, y: -35.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.375,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.66311,
                            .LeftShank: 0.0,
                            .RightFoot: -0.933091,
                            .RightShank: 5.31098,
                            .LowerBody: -0.13413,
                            .LeftThigh: -0.165539,
                            .Head: -0.20978,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.669349,
                            .RightUpperArm: 1.29542,
                            .UpperBody: 0.575309,
                            .RightThigh: 1.63069,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -28.0, y: 114.0)),
                    angleCurve: .CubicEaseOut,
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe(
                    time: 0.375,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.63635,
                            .LeftShank: 1.39098,
                            .RightFoot: -0.0918853,
                            .RightShank: 5.26506,
                            .LowerBody: 0.370891,
                            .LeftThigh: -1.68166,
                            .Head: 0.610689,
                            .RightForearm: 6.01047,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 5.07431,
                            .UpperBody: -0.370891,
                            .RightThigh: 0.565783,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 23.5, y: -23.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.0441427,
                            .LeftShank: 1.51111,
                            .RightFoot: -0.0918853,
                            .RightShank: 5.26506,
                            .LowerBody: -0.839862,
                            .LeftThigh: -0.97091,
                            .Head: 0.104871,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.0270381,
                            .RightUpperArm: 1.77606,
                            .UpperBody: 0.555344,
                            .RightThigh: 0.565783,
                            .LeftForearm: 1.10393],
                        position: CGPoint(x: 96.5, y: -11.5)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.360366,
                            .LeftShank: 0.00660872,
                            .RightFoot: 0.247793,
                            .RightShank: 6.27873,
                            .LowerBody: -0.0604089,
                            .LeftThigh: -0.0277284,
                            .Head: 0.0333487,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.0579829,
                            .RightUpperArm: 0.0555868,
                            .UpperBody: 0.0591646,
                            .RightThigh: -0.0106775,
                            .LeftForearm: 0.00482786],
                        position: CGPoint(x: 23.7443, y: -22.9687)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut)],
            levelOfIntensity: 4,
            name: "Jump and wave")
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.39289,
                            .LeftShank: 1.92811,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: 0.423191,
                            .LeftThigh: -2.18445,
                            .Head: 0.310735,
                            .RightForearm: 5.2857,
                            .LeftFoot: -0.0470883,
                            .RightUpperArm: 1.39335,
                            .UpperBody: 0.246264,
                            .RightThigh: 0.0,
                            .LeftForearm: 0.905939],
                        position: CGPoint(x: -162.0, y: -82.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.761523,
                            .LeftShank: 1.92811,
                            .RightFoot: -0.432979,
                            .RightShank: 0.0,
                            .LowerBody: 0.0264815,
                            .LeftThigh: -2.18445,
                            .Head: -0.790229,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.0470883,
                            .RightUpperArm: 1.8682,
                            .UpperBody: 0.994825,
                            .RightThigh: 1.48203,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -270.0, y: -79.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe(
                    time: 0.375,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.788056,
                            .LeftShank: 0.0,
                            .RightFoot: -0.38518,
                            .RightShank: 0.0,
                            .LowerBody: 0.27472,
                            .LeftThigh: -0.0543758,
                            .Head: 0.463117,
                            .RightForearm: 1.19173,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 1.42856,
                            .UpperBody: -0.673243,
                            .RightThigh: 0.953517,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -123.5, y: 75.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn,
                    interruptable: false),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.0,
                            .LeftShank: 2.24074,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: 5.69472,
                            .LeftThigh: -1.43833,
                            .Head: 0.0189726,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.302371,
                            .RightUpperArm: 1.01947,
                            .UpperBody: -1.79363,
                            .RightThigh: 0.385056,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 35.0, y: 184.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 5.94507,
                            .LeftShank: 2.24074,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: 5.99385,
                            .LeftThigh: -1.43833,
                            .Head: 0.0189726,
                            .RightForearm: 5.05911,
                            .LeftFoot: -0.302371,
                            .RightUpperArm: 7.98923,
                            .UpperBody: -3.6334,
                            .RightThigh: -6.99757,
                            .LeftForearm: 4.80243],
                        position: CGPoint(x: 6.0, y: 164.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.851126,
                            .LeftShank: 2.24074,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: -0.0219933,
                            .LeftThigh: -1.43833,
                            .Head: -0.131217,
                            .RightForearm: 5.05911,
                            .LeftFoot: -1.54577,
                            .RightUpperArm: 7.98923,
                            .UpperBody: 0.617303,
                            .RightThigh: -6.99757,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 188.5, y: 109.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.23459,
                            .LeftShank: 2.085,
                            .RightFoot: -5.17274,
                            .RightShank: 4.44939,
                            .LowerBody: 0.577392,
                            .LeftThigh: -2.57121,
                            .Head: 0.692128,
                            .RightForearm: 0.0,
                            .LeftFoot: -1.54577,
                            .RightUpperArm: 1.66165,
                            .UpperBody: -0.728855,
                            .RightThigh: 0.819015,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 216.5, y: -63.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 6.27798,
                            .LeftShank: 0.00529552,
                            .RightFoot: -6.28036,
                            .RightShank: 6.27853,
                            .LowerBody: 0.00146645,
                            .LeftThigh: -0.00653028,
                            .Head: 0.0017578,
                            .RightForearm: 0.0,
                            .LeftFoot: -0.0039258,
                            .RightUpperArm: 0.00422025,
                            .UpperBody: -0.00185114,
                            .RightThigh: 0.00208008,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 204.502, y: 0.833069)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut
                )],
            levelOfIntensity: 5,
            name: "Big cart wheel")
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.5,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.13152,
                            .LeftShank: 1.10944,
                            .RightFoot: 0.0,
                            .RightShank: 5.08803,
                            .LowerBody: -0.206717,
                            .LeftThigh: -0.747922,
                            .Head: 0.237016,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0359586,
                            .RightUpperArm: 1.82182,
                            .UpperBody: 0.206717,
                            .RightThigh: 0.725701,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 3.83331, y: -62.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.241046831011772,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.28481,
                            .LeftShank: 0.558894,
                            .RightFoot: 0.0,
                            .RightShank: 5.56802,
                            .LowerBody: 0.0719755,
                            .LeftThigh: -0.18049,
                            .Head: 0.237016,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0359586,
                            .RightUpperArm: 1.05351,
                            .UpperBody: 0.26964,
                            .RightThigh: 0.555932,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -73.1667, y: 19.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.227272734045982,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.76938,
                            .LeftShank: 0.558894,
                            .RightFoot: 0.0,
                            .RightShank: 5.56802,
                            .LowerBody: -0.372415,
                            .LeftThigh: -0.18049,
                            .Head: -0.671813,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0359586,
                            .RightUpperArm: 1.70516,
                            .UpperBody: 0.621896,
                            .RightThigh: 0.555932,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -125.167, y: 68.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.241046831011772,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.3753,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: -0.392953,
                            .LeftThigh: -0.426746,
                            .Head: -0.119839,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0359586,
                            .RightUpperArm: 0.647756,
                            .UpperBody: 0.00900853,
                            .RightThigh: -0.219047,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -116.167, y: 124.5)),
                    angleCurve: .SineEaseInOut,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.241046831011772,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.97359,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: -0.168855,
                            .LeftThigh: -0.426746,
                            .Head: 0.178806,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0359586,
                            .RightUpperArm: 1.95055,
                            .UpperBody: -0.215089,
                            .RightThigh: -0.219047,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -103.167, y: 163.0)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.234159782528877,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.31207,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .RightShank: 0.0,
                            .LowerBody: -0.226395,
                            .LeftThigh: -0.426746,
                            .Head: 0.178806,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0359586,
                            .RightUpperArm: 1.23008,
                            .UpperBody: -0.157549,
                            .RightThigh: -0.219047,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -43.6667, y: 194.5)),
                    angleCurve: .SineEaseInOut,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.247933879494667,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.40447,
                            .LeftShank: 2.20359,
                            .RightFoot: -1.28038,
                            .RightShank: 0.0,
                            .LowerBody: 0.257409,
                            .LeftThigh: -1.24126,
                            .Head: 0.178806,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0359586,
                            .RightUpperArm: 2.11189,
                            .UpperBody: -0.157549,
                            .RightThigh: -0.219047,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -3.16669, y: 227.0)),
                    angleCurve: .SineEaseInOut,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.247933879494667,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.12557,
                            .LeftShank: 2.19124,
                            .RightFoot: -1.31586,
                            .RightShank: 0.0,
                            .LowerBody: 0.229356,
                            .LeftThigh: -0.556239,
                            .Head: 0.178806,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.855654,
                            .RightUpperArm: 0.889348,
                            .UpperBody: 0.115292,
                            .RightThigh: -0.219047,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -8.66669, y: 191.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.261707991361618,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.3769,
                            .LeftShank: 1.88297,
                            .RightFoot: -1.31586,
                            .RightShank: 0.0,
                            .LowerBody: -0.145992,
                            .LeftThigh: -0.541624,
                            .Head: -0.308372,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.452692,
                            .RightUpperArm: 2.02392,
                            .UpperBody: 0.152403,
                            .RightThigh: -0.219047,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 3.83331, y: 179.0)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.241046831011772,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.03815,
                            .LeftShank: 2.19124,
                            .RightFoot: -1.31586,
                            .RightShank: 0.0,
                            .LowerBody: -0.157694,
                            .LeftThigh: -0.556239,
                            .Head: -0.308372,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.855654,
                            .RightUpperArm: 1.04782,
                            .UpperBody: 0.152403,
                            .RightThigh: -0.219047,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 14.3333, y: 174.0)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.241046831011772,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.43134,
                            .LeftShank: 1.40063,
                            .RightFoot: -6.03973,
                            .RightShank: 5.76117,
                            .LowerBody: -0.0234327,
                            .LeftThigh: -0.584319,
                            .Head: -0.308372,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.342788,
                            .RightUpperArm: 1.7063,
                            .UpperBody: -0.00936353,
                            .RightThigh: -0.194061,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 28.6666, y: 155.0)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.247933879494667,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.04896,
                            .LeftShank: 0.945653,
                            .RightFoot: -0.960496,
                            .RightShank: 0.0,
                            .LowerBody: 0.0320646,
                            .LeftThigh: -0.499074,
                            .Head: -0.268976,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.73959,
                            .RightUpperArm: 1.04337,
                            .UpperBody: 0.041642,
                            .RightThigh: -0.336119,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 24.1666, y: 135.0)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.247933879494667,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.14561,
                            .LeftShank: 1.48506,
                            .RightFoot: -0.897433,
                            .RightShank: 5.71679,
                            .LowerBody: -0.192296,
                            .LeftThigh: -1.52235,
                            .Head: -0.00250626,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.779812,
                            .RightUpperArm: 1.65731,
                            .UpperBody: 0.314294,
                            .RightThigh: -0.67105,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 41.6666, y: 93.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.268595039844513,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.16191,
                            .LeftShank: 0.813434,
                            .RightFoot: -6.03973,
                            .RightShank: 5.34277,
                            .LowerBody: 0.0283036,
                            .LeftThigh: -0.892119,
                            .Head: -0.00250626,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.7242,
                            .RightUpperArm: 0.637067,
                            .UpperBody: 0.0492746,
                            .RightThigh: 0.483889,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: -10.0, y: 33.1667)),
                    angleCurve: .Linear,
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe(
                    time: 0.234159782528877,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.37192,
                            .LeftShank: 1.13463,
                            .RightFoot: -6.03973, 
                            .RightShank: 5.36199, 
                            .LowerBody: -0.198498, 
                            .LeftThigh: -1.05857, 
                            .Head: -0.0017724, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.7242, 
                            .RightUpperArm: 1.84778, 
                            .UpperBody: 0.0492746, 
                            .RightThigh: 0.777828, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -19.5, y: -13.3333)), 
                    angleCurve: .Linear, 
                    positionCurve: .Linear),
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -0.965937, 
                            .LeftShank: 1.94761, 
                            .RightFoot: -5.05982, 
                            .RightShank: 4.17693, 
                            .LowerBody: -0.198498, 
                            .LeftThigh: -1.06792, 
                            .Head: -0.0017724, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.895015, 
                            .RightUpperArm: 0.838784, 
                            .UpperBody: 0.0492746, 
                            .RightThigh: 1.38656, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 1.5, y: -108.833)), 
                    angleCurve: .Linear, 
                    positionCurve: .Linear)],
            levelOfIntensity: 5,
            name: "Fly away"
        )
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -1.68256, 
                            .LeftShank: 2.38926, 
                            .RightFoot: 0.716209, 
                            .RightShank: 4.25645, 
                            .LowerBody: -0.494918, 
                            .LeftThigh: -1.55156, 
                            .Head: 0.190241, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.632249, 
                            .RightUpperArm: 2.72856, 
                            .UpperBody: 0.860665, 
                            .RightThigh: 0.985165, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -2.5, y: -109.5)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -1.68256, 
                            .LeftShank: 0.481555, 
                            .RightFoot: -0.887495, 
                            .RightShank: 0.0, 
                            .LowerBody: 0.0688297, 
                            .LeftThigh: 0.402869, 
                            .Head: 0.190241, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.814134, 
                            .RightUpperArm: 0.662779, 
                            .UpperBody: -1.21366, 
                            .RightThigh: 0.874316, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 23.5, y: 100.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn,
                    interruptable: false),
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.01688, 
                            .LeftShank: 0.330607, 
                            .RightFoot: -0.887495, 
                            .RightShank: 0.0, 
                            .LowerBody: 6.30651, 
                            .LeftThigh: -0.388467, 
                            .Head: 0.190241, 
                            .RightForearm: 0.693995, 
                            .LeftFoot: 0.814134, 
                            .RightUpperArm: 2.63606, 
                            .UpperBody: -2.13316, 
                            .RightThigh: 0.312052, 
                            .LeftForearm: 5.20896], 
                        position: CGPoint(x: -2.5, y: 155.5)), 
                    angleCurve: .Linear, 
                    positionCurve: .Linear,
                    interruptable: false),
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 5.07309, 
                            .LeftShank: 0.330607, 
                            .RightFoot: -0.887495, 
                            .RightShank: 4.36025, 
                            .LowerBody: 6.21955, 
                            .LeftThigh: -0.388467, 
                            .Head: 0.0247858, 
                            .RightForearm: 2.46958, 
                            .LeftFoot: 1.86565, 
                            .RightUpperArm: 0.933726, 
                            .UpperBody: -3.15674, 
                            .RightThigh: -5.27254, 
                            .LeftForearm: 4.0159], 
                        position: CGPoint(x: 34.0, y: -131.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe( 
                    time: 0.375, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.10068, 
                            .LeftShank: 1.79974, 
                            .RightFoot: -0.887495, 
                            .RightShank: 4.36025, 
                            .LowerBody: 6.01369, 
                            .LeftThigh: -7.35623, 
                            .Head: 0.190241, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.179052, 
                            .RightUpperArm: 2.63942, 
                            .UpperBody: -3.19539, 
                            .RightThigh: -5.27254, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -9.5, y: 145.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn,
                    interruptable: false),
                Keyframe( 
                    time: 0.375, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.79322, 
                            .LeftShank: 1.22219, 
                            .RightFoot: -0.887495, 
                            .RightShank: 5.45051, 
                            .LowerBody: 0.17351, 
                            .LeftThigh: -7.03089, 
                            .Head: 0.190241, 
                            .RightForearm: 1.03877, 
                            .LeftFoot: 0.179052, 
                            .RightUpperArm: 1.1816, 
                            .UpperBody: 0.300171, 
                            .RightThigh: -6.06608, 
                            .LeftForearm: 5.38584], 
                        position: CGPoint(x: 37.5, y: -25.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.93731, 
                            .LeftShank: 2.07085, 
                            .RightFoot: -6.14336, 
                            .RightShank: 4.35246, 
                            .LowerBody: 0.158027, 
                            .LeftThigh: -1.76372, 
                            .Head: 0.190241, 
                            .RightForearm: 0.63703, 
                            .LeftFoot: -1.02618, 
                            .RightUpperArm: 1.68075, 
                            .UpperBody: 0.280537, 
                            .RightThigh: 0.720994, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 57.5, y: -100.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 6.28103, 
                            .LeftShank: 0.00190043, 
                            .RightFoot: -6.28306, 
                            .RightShank: 6.28141, 
                            .LowerBody: 0.000145033, 
                            .LeftThigh: -0.00161874, 
                            .Head: 0.000174597, 
                            .RightForearm: 0.000584662, 
                            .LeftFoot: -0.000941753, 
                            .RightUpperArm: 0.00154257, 
                            .UpperBody: 0.000257462, 
                            .RightThigh: 0.000661671, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0527344, y: -0.0917664)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut)], 
            levelOfIntensity: 5,
            name: "Bump head")
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -0.0659904, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .RightShank: 5.28082, 
                            .LowerBody: 5.52507, 
                            .LeftThigh: -1.06264, 
                            .Head: 0.37134, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 2.76725, 
                            .UpperBody: -4.47637, 
                            .RightThigh: 1.8783, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -84.5, y: -26.5)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.9193, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .RightShank: 0.0, 
                            .LowerBody: 0.312473, 
                            .LeftThigh: 4.97892, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.712204, 
                            .UpperBody: -0.404892, 
                            .RightThigh: -0.1484, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 134.5, y: 6.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 2.83168, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .RightShank: 0.0, 
                            .LowerBody: 0.546089, 
                            .LeftThigh: 4.97892, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 5.43739, 
                            .UpperBody: -1.80786, 
                            .RightThigh: 1.19151, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 172.5, y: -16.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -0.91226, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .RightShank: 0.0, 
                            .LowerBody: 0.293799, 
                            .LeftThigh: -1.70265, 
                            .Head: 0.209266, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 2.2725, 
                            .UpperBody: -0.400535, 
                            .RightThigh: 0.132283, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 74.0, y: 8.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.498019, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .RightShank: 0.0, 
                            .LowerBody: -0.652721, 
                            .LeftThigh: -0.0891908, 
                            .Head: 0.499626, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 2.44191, 
                            .UpperBody: 0.545985, 
                            .RightThigh: 0.132283, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 101.5, y: 11.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.00089097, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .RightShank: 0.0, 
                            .LowerBody: -0.00116783, 
                            .LeftThigh: -0.000159591, 
                            .Head: 0.000893891, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.00436878, 
                            .UpperBody: 0.000976861, 
                            .RightThigh: 0.000236675, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 112.076, y: 8.98422)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut)], 
            levelOfIntensity: 3,
            name: "Side split kick"
        )
        
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 1.38076, 
                            .RightFoot: 0.0, 
                            .RightShank: 4.77038, 
                            .LowerBody: -0.0561044, 
                            .LeftThigh: -0.76494, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.0204053, 
                            .RightThigh: 0.69511, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 15.0, y: -67.5)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.34114, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.973517, 
                            .RightShank: 0.0, 
                            .LowerBody: 0.0277992, 
                            .LeftThigh: -0.618943, 
                            .Head: 0.257628, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.843483, 
                            .RightUpperArm: 1.54231, 
                            .UpperBody: -0.0634984, 
                            .RightThigh: 0.257164, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 67.0, y: 20.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 1.38076, 
                            .RightFoot: 0.0, 
                            .RightShank: 4.77038, 
                            .LowerBody: -0.294188, 
                            .LeftThigh: -0.76494, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.239894, 
                            .RightThigh: 0.69511, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 99.5, y: -65.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -1.15791, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.1439, 
                            .RightShank: 0.0, 
                            .LowerBody: -0.153963, 
                            .LeftThigh: -0.0663301, 
                            .Head: 0.282425, 
                            .RightForearm: 5.68778, 
                            .LeftFoot: 0.497367, 
                            .RightUpperArm: 1.00651, 
                            .UpperBody: 0.0996686, 
                            .RightThigh: -0.0282129, 
                            .LeftForearm: 0.493522], 
                        position: CGPoint(x: 135.5, y: 29.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 1.38076, 
                            .RightFoot: 0.0, 
                            .RightShank: 4.77038, 
                            .LowerBody: -0.290864, 
                            .LeftThigh: -0.76494, 
                            .Head: 0.358382, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.378142, 
                            .RightThigh: 0.69511, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 234.0, y: -59.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.61474, 
                            .LeftShank: 0.0, 
                            .RightFoot: -1.14714, 
                            .RightShank: 0.0, 
                            .LowerBody: -0.00360346, 
                            .LeftThigh: -0.558298, 
                            .Head: -0.202742, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.594654, 
                            .RightUpperArm: 1.41933, 
                            .UpperBody: 0.230402, 
                            .RightThigh: 0.606682, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -9.0, y: 318.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut,
                    interruptable: false),
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 1.12903, 
                            .RightFoot: -5.47815, 
                            .RightShank: 4.97523, 
                            .LowerBody: -0.0561044, 
                            .LeftThigh: -1.20089, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.0204053, 
                            .RightThigh: 1.14936, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 15.0, y: -67.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.5, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.00510991, 
                            .RightFoot: -6.27954, 
                            .RightShank: 6.27726, 
                            .LowerBody: -0.000253927, 
                            .LeftThigh: -0.00543511, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 9.23499e-05, 
                            .RightThigh: 0.00520205, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -77.3415, y: 6.68631)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut)], 
            levelOfIntensity: 3,
            name: "Hop & jump")
    }

}