//
//  HipHopMoves.swift
//  AniDraw
//
//  Created by Mike on 7/25/16.
//  Copyright © 2016 yanjingzz. All rights reserved.
//

import Foundation
struct HipHopMoves {
    static func createAll() {
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 5.6741,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .LeftThigh: 0.0,
                            .LowerBody: 0.005988,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.15999,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0,
                            .LeftForearm: 4.8227],
                        position: CGPoint(x: 0.0, y: 0.0)),
                    angleCurve: .Linear,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.02839,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .LeftThigh: 0.0,
                            .LowerBody: 0.0289774,
                            .RightShank: 0.0,
                            .Head: -0.0380788,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.189832,
                            .UpperBody: -0.0289774,
                            .RightThigh: 0.0, 
                            .LeftForearm: 1.1325], 
                        position: CGPoint(x: 0.0, y: 0.0)), 
                    angleCurve: .Linear, 
                    positionCurve: .Linear), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -1.21815, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .LeftThigh: 0.0, 
                            .LowerBody: 0.327098, 
                            .RightShank: 0.0, 
                            .Head: 0.328706, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.384985, 
                            .UpperBody: -0.327098, 
                            .RightThigh: 0.0, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0, y: 0.0)), 
                    angleCurve: .Linear, 
                    positionCurve: .Linear), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -0.148428, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .LeftThigh: 0.0, 
                            .LowerBody: -0.238609, 
                            .RightShank: 0.0, 
                            .Head: -0.369636, 
                            .RightForearm: 5.74951, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.536392, 
                            .UpperBody: 0.238609, 
                            .RightThigh: 0.0, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0, y: 0.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .Linear), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .LeftThigh: 0.0, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 5.11695, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 1.29939, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.0, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0, y: 0.0)), 
                    angleCurve: .Linear, 
                    positionCurve: .Linear), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .LeftThigh: 0.0, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 1.06974, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.928701, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.0, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0, y: 0.0)), 
                    angleCurve: .Linear, 
                    positionCurve: .Linear), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .LeftThigh: 0.0, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 1.67712, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.0, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0, y: 0.0)), 
                    angleCurve: .Linear, 
                    positionCurve: .EaseIn)], 
            levelOfIntensity: 4,
            style: .HipHop,
            name: "Arms Wave")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.3833,
                            .LeftShank: 0.0,
                            .RightFoot: 0.516422,
                            .LeftThigh: -0.336598,
                            .LowerBody: -0.760491,
                            .RightShank: 0.0,
                            .Head: 6.04994,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: -1.99915,
                            .UpperBody: 1.11021,
                            .RightThigh: -0.0202475,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 15.5, y: 6.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.07286,
                            .LeftShank: 1.51194,
                            .RightFoot: -5.4095,
                            .LeftThigh: -0.634579,
                            .LowerBody: -0.736111,
                            .RightShank: 4.76237,
                            .Head: 0.719825,
                            .RightForearm: 0.0,
                            .LeftFoot: -1.15403,
                            .RightUpperArm: 2.22396,
                            .UpperBody: 0.736111,
                            .RightThigh: 0.77292,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 35.0, y: -37.5)),
                    angleCurve: .Linear,
                    positionCurve: .Linear),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.0,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .LeftThigh: 0.0,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.0,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 78.0, y: -2.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 1.2465,
                            .LeftShank: 1.57927,
                            .RightFoot: -4.84869,
                            .LeftThigh: -0.723049,
                            .LowerBody: 0.0,
                            .RightShank: 4.66209,
                            .Head: 0.0,
                            .RightForearm: 4.76657,
                            .LeftFoot: -0.957586,
                            .RightUpperArm: 5.17251,
                            .UpperBody: 0.0,
                            .RightThigh: 0.634174,
                            .LeftForearm: 1.69469],
                        position: CGPoint(x: 95.5, y: -50.5)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.0,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .LeftThigh: 0.0,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.0,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 78.0, y: -2.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn)],
            levelOfIntensity: 2,
            style: .HipHop,
            name: "Arm Circle")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.020368,
                            .LeftShank: 0.0,
                            .RightFoot: 0.544315,
                            .LeftThigh: -0.216259,
                            .LowerBody: 0.382481,
                            .RightShank: 5.14107,
                            .Head: 0.316852,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.336859,
                            .UpperBody: -0.243261,
                            .RightThigh: 0.561591,
                            .LeftForearm: 1.41581],
                        position: CGPoint(x: 1.0, y: 2.5)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.1443,
                            .LeftShank: 0.0,
                            .RightFoot: 0.544315,
                            .LeftThigh: -0.550683,
                            .LowerBody: -0.390607,
                            .RightShank: 5.14107,
                            .Head: -0.142012,
                            .RightForearm: 2.70783,
                            .LeftFoot: 0.349101,
                            .RightUpperArm: 1.363,
                            .UpperBody: 0.390607,
                            .RightThigh: 0.561591,
                            .LeftForearm: 2.39671],
                        position: CGPoint(x: 102.5, y: -16.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.40254,
                            .LeftShank: 0.0,
                            .RightFoot: 0.544315,
                            .LeftThigh: -0.550683,
                            .LowerBody: 0.035827,
                            .RightShank: 5.14107,
                            .Head: 0.336037,
                            .RightForearm: 3.93492,
                            .LeftFoot: 0.349101,
                            .RightUpperArm: 1.07914,
                            .UpperBody: -0.146484,
                            .RightThigh: 0.561591,
                            .LeftForearm: 3.84781],
                        position: CGPoint(x: 102.5, y: -16.5)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.56904,
                            .LeftShank: 0.0,
                            .RightFoot: 0.544315,
                            .LeftThigh: -0.408422,
                            .LowerBody: -0.425651,
                            .RightShank: 5.31995,
                            .Head: -0.342849,
                            .RightForearm: 2.39574,
                            .LeftFoot: 0.349101,
                            .RightUpperArm: 1.71412,
                            .UpperBody: 0.314994,
                            .RightThigh: 0.545839,
                            .LeftForearm: 2.57472],
                        position: CGPoint(x: 109.5, y: -6.5)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.487407,
                            .LeftShank: 0.0,
                            .RightFoot: -0.0776056,
                            .LeftThigh: -0.183608,
                            .LowerBody: 0.284718,
                            .RightShank: 0.0,
                            .Head: 0.217605,
                            .RightForearm: 3.95028,
                            .LeftFoot: 0.349101,
                            .RightUpperArm: 1.34442,
                            .UpperBody: -0.365425,
                            .RightThigh: 0.126382,
                            .LeftForearm: 1.77277],
                        position: CGPoint(x: 113.0, y: -1.5)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.632483,
                            .LeftShank: 0.983903,
                            .RightFoot: 0.0273228,
                            .LeftThigh: -0.571814,
                            .LowerBody: -0.427892,
                            .RightShank: 0.0,
                            .Head: 0.272936,
                            .RightForearm: 2.6435,
                            .LeftFoot: -0.45918,
                            .RightUpperArm: 1.58189,
                            .UpperBody: 0.190518,
                            .RightThigh: 0.226774,
                            .LeftForearm: 1.43577],
                        position: CGPoint(x: 137.0, y: 1.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.89137,
                            .LeftShank: 0.983903,
                            .RightFoot: -0.429139,
                            .LeftThigh: -0.571814,
                            .LowerBody: 0.409251,
                            .RightShank: 0.0,
                            .Head: 0.608635,
                            .RightForearm: 4.26904,
                            .LeftFoot: -0.45918,
                            .RightUpperArm: 1.34798,
                            .UpperBody: -0.489957,
                            .RightThigh: 0.608769,
                            .LeftForearm: 3.73383],
                        position: CGPoint(x: 48.5, y: -18.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.45941,
                            .LeftShank: 0.983903,
                            .RightFoot: -0.429139,
                            .LeftThigh: -0.571814,
                            .LowerBody: -0.460047,
                            .RightShank: 0.0,
                            .Head: -0.345973,
                            .RightForearm: 2.58688,
                            .LeftFoot: -0.45918,
                            .RightUpperArm: 1.72125,
                            .UpperBody: 0.379341,
                            .RightThigh: 0.608769,
                            .LeftForearm: 2.42297],
                        position: CGPoint(x: 48.5, y: -18.0)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.89137,
                            .LeftShank: 0.983903,
                            .RightFoot: -0.429139,
                            .LeftThigh: -0.571814,
                            .LowerBody: 0.409251,
                            .RightShank: 0.0,
                            .Head: 0.608635, 
                            .RightForearm: 4.26904, 
                            .LeftFoot: -0.45918, 
                            .RightUpperArm: 1.34798, 
                            .UpperBody: -0.489957, 
                            .RightThigh: 0.608769, 
                            .LeftForearm: 3.73383], 
                        position: CGPoint(x: 48.5, y: -18.0)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -1.44664, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.429139, 
                            .LeftThigh: -0.000600338, 
                            .LowerBody: -0.354108, 
                            .RightShank: 0.0, 
                            .Head: -0.182428, 
                            .RightForearm: 2.55547, 
                            .LeftFoot: -0.00199783, 
                            .RightUpperArm: 1.68927, 
                            .UpperBody: 0.273401, 
                            .RightThigh: 0.394864, 
                            .LeftForearm: 2.5467], 
                        position: CGPoint(x: 24.5, y: 4.5)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut)], 
            levelOfIntensity: 3,
            style: .HipHop,
            name: "Shoulder Move")
        
        _ = DanceMove( 
            keyframes:
            [
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.702168, 
                            .LeftShank: 1.13269, 
                            .RightFoot: -5.80728, 
                            .LeftThigh: -1.05126, 
                            .LowerBody: 0.0, 
                            .RightShank: 5.13521, 
                            .Head: -0.453325, 
                            .RightForearm: 4.79598, 
                            .LeftFoot: -0.390734, 
                            .RightUpperArm: -0.641062, 
                            .UpperBody: 0.0, 
                            .RightThigh: 1.02036, 
                            .LeftForearm: 2.36904], 
                        position: CGPoint(x: 94.0, y: -37.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.0, 
                            .RightFoot: -0.157845, 
                            .LeftThigh: -0.120105, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0268275, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.0, 
                            .RightThigh: -0.0130384, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 163.5, y: 10.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.5909, 
                            .LeftShank: 1.29859, 
                            .RightFoot: -5.85501, 
                            .LeftThigh: -1.45332, 
                            .LowerBody: -0.0275811, 
                            .RightShank: 4.81017, 
                            .Head: 0.449727, 
                            .RightForearm: 1.08617, 
                            .LeftFoot: -0.21576, 
                            .RightUpperArm: 1.55604, 
                            .UpperBody: 0.0275792, 
                            .RightThigh: 1.46895, 
                            .LeftForearm: 5.21526], 
                        position: CGPoint(x: 96.5, y: -74.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .LeftThigh: 0.0, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.0, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0, y: 0.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn)], 
            levelOfIntensity: 2,
            style: .HipHop,
            name: "Up & Down Step")
        
        _ = DanceMove( 
            keyframes:
            [
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.69621, 
                            .LeftShank: 1.22496, 
                            .RightFoot: 0.0, 
                            .LeftThigh: 0.318684, 
                            .LowerBody: -0.214051, 
                            .RightShank: 0.0, 
                            .Head: -0.187213, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.261615, 
                            .UpperBody: -0.26378, 
                            .RightThigh: 0.357522, 
                            .LeftForearm: 5.43448], 
                        position: CGPoint(x: 29.5, y: 9.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 3.40042, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.794117, 
                            .LeftThigh: 0.451439, 
                            .LowerBody: 0.327923, 
                            .RightShank: 0.0, 
                            .Head: -0.432165, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.778579, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: -0.327923, 
                            .RightThigh: -0.360637, 
                            .LeftForearm: 5.51035], 
                        position: CGPoint(x: 16.5, y: -6.5)), 
                    angleCurve: .Linear, 
                    positionCurve: .Linear), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 1.67041, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.54307, 
                            .LeftThigh: -0.212526, 
                            .LowerBody: 1.09998, 
                            .RightShank: 5.2732, 
                            .Head: -0.432127, 
                            .RightForearm: 5.504, 
                            .LeftFoot: 0.178432, 
                            .RightUpperArm: 1.41484, 
                            .UpperBody: -1.10349, 
                            .RightThigh: 0.803418, 
                            .LeftForearm: 1.20953], 
                        position: CGPoint(x: 72.5, y: 17.5)), 
                    angleCurve: .Linear, 
                    positionCurve: .Linear), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.174585, 
                            .LeftShank: 0.0, 
                            .RightFoot: -6.17233, 
                            .LeftThigh: -0.355227, 
                            .LowerBody: -0.258544, 
                            .RightShank: 5.32931, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.517481, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.0, 
                            .RightThigh: 1.22543, 
                            .LeftForearm: 0.500234], 
                        position: CGPoint(x: 182.0, y: -30.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -0.923309, 
                            .LeftShank: 1.65519, 
                            .RightFoot: 0.130953, 
                            .LeftThigh: -0.864989, 
                            .LowerBody: -1.08956, 
                            .RightShank: 0.0, 
                            .Head: 0.585518, 
                            .RightForearm: 0.262875, 
                            .LeftFoot: -0.841241, 
                            .RightUpperArm: 1.77042, 
                            .UpperBody: 0.792805, 
                            .RightThigh: 0.234609, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 262.0, y: 14.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: -1.34361, 
                            .LeftShank: 1.38805, 
                            .RightFoot: -0.757734, 
                            .LeftThigh: -1.07457, 
                            .LowerBody: -1.10715, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.933923, 
                            .RightUpperArm: 3.98658, 
                            .UpperBody: 1.10715, 
                            .RightThigh: 0.907677, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 87.0, y: -39.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.351577, 
                            .LeftThigh: -0.0196261, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.159686, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.0, 
                            .RightThigh: -0.0640969, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 35.5, y: 19.0)), 
                    angleCurve: .EaseInOut, 
                    positionCurve: .EaseInOut)], 
            levelOfIntensity: 3,
            style: .HipHop,
            name: "Cycle Step")

        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.86089,
                            .LeftShank: 2.02635,
                            .RightFoot: -5.38221,
                            .LeftThigh: -1.11423,
                            .LowerBody: 0.0,
                            .RightShank: 4.1474,
                            .Head: 0.0,
                            .RightForearm: 3.54428,
                            .LeftFoot: -0.629924,
                            .RightUpperArm: 2.05594,
                            .UpperBody: 0.0,
                            .RightThigh: 1.11453,
                            .LeftForearm: 2.89288],
                        position: CGPoint(x: 14.0, y: -90.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.0,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .LeftThigh: 0.0,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.0,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 0.0, y: 0.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -1.82065,
                            .LeftShank: 1.98619,
                            .RightFoot: -5.20064,
                            .LeftThigh: -1.13152,
                            .LowerBody: -0.0275811,
                            .RightShank: 4.20669,
                            .Head: 0.0,
                            .RightForearm: 3.48684,
                            .LeftFoot: -0.896164,
                            .RightUpperArm: 1.77207,
                            .UpperBody: 0.0275792,
                            .RightThigh: 1.18162,
                            .LeftForearm: 2.76152],
                        position: CGPoint(x: 1.5, y: -85.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.0,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .LeftThigh: 0.0,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.0,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 0.0, y: 0.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn)],
            levelOfIntensity: 1,
            style: .HipHop,
            name: "Up & Down")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.912676,
                            .LeftShank: 2.02635,
                            .RightFoot: -5.15051,
                            .LeftThigh: -1.11423,
                            .LowerBody: 0.0,
                            .RightShank: 4.1474,
                            .Head: 0.0,
                            .RightForearm: 4.25412,
                            .LeftFoot: -1.06081,
                            .RightUpperArm: -0.809332,
                            .UpperBody: 0.0,
                            .RightThigh: 1.11453,
                            .LeftForearm: 2.00587],
                        position: CGPoint(x: 14.0, y: -90.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.0,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .LeftThigh: 0.0,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.0,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 0.0, y: 0.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 4.5909,
                            .LeftShank: 1.98619,
                            .RightFoot: -5.20064,
                            .LeftThigh: -1.13152,
                            .LowerBody: -0.0275811,
                            .RightShank: 4.20669,
                            .Head: -0.156357,
                            .RightForearm: 1.08617,
                            .LeftFoot: -0.896164,
                            .RightUpperArm: 1.55604,
                            .UpperBody: 0.0275792,
                            .RightThigh: 1.18162,
                            .LeftForearm: 5.21526],
                        position: CGPoint(x: 1.5, y: -85.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.0,
                            .LeftShank: 0.0,
                            .RightFoot: 0.0,
                            .LeftThigh: 0.0,
                            .LowerBody: 0.0,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.0,
                            .RightUpperArm: 0.0,
                            .UpperBody: 0.0,
                            .RightThigh: 0.0,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 0.0, y: 0.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn)],
            levelOfIntensity: 1,
            style: .HipHop,
            name: "Up & Down W/ Hug")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.710953,
                            .LeftShank: 1.16005,
                            .RightFoot: -5.62756,
                            .LeftThigh: -0.485023,
                            .LowerBody: 0.0,
                            .RightShank: 5.14876,
                            .Head: 0.0,
                            .RightForearm: 4.48273,
                            .LeftFoot: -0.801087,
                            .RightUpperArm: -0.565734,
                            .UpperBody: 0.0,
                            .RightThigh: 0.505571,
                            .LeftForearm: 2.1386],
                        position: CGPoint(x: 14.5, y: -19.0)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.158938,
                            .LeftShank: 0.655272,
                            .RightFoot: -5.80728,
                            .LeftThigh: -0.296921,
                            .LowerBody: 0.0,
                            .RightShank: 5.69246,
                            .Head: 0.0,
                            .RightForearm: 4.69598,
                            .LeftFoot: -0.472361,
                            .RightUpperArm: -0.147127,
                            .UpperBody: 0.0,
                            .RightThigh: 0.233506,
                            .LeftForearm: 1.5068],
                        position: CGPoint(x: 11.5, y: 0.0)),
                    angleCurve: .EaseIn,
                    positionCurve: .EaseIn),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 0.912676, 
                            .LeftShank: 2.02635, 
                            .RightFoot: -5.15051, 
                            .LeftThigh: -1.11423, 
                            .LowerBody: 0.0, 
                            .RightShank: 4.1474, 
                            .Head: 0.0, 
                            .RightForearm: 4.25412, 
                            .LeftFoot: -1.06081, 
                            .RightUpperArm: -0.809332, 
                            .UpperBody: 0.0, 
                            .RightThigh: 1.11453, 
                            .LeftForearm: 2.00587], 
                        position: CGPoint(x: 14.0, y: -90.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.125, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.471579, 
                            .RightFoot: -5.6266, 
                            .LeftThigh: -0.262646, 
                            .LowerBody: 0.0, 
                            .RightShank: 5.62195, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: -0.219561, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.411745, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: -1.0, y: -21.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 4.5909, 
                            .LeftShank: 1.98619, 
                            .RightFoot: -5.20064, 
                            .LeftThigh: -1.13152, 
                            .LowerBody: -0.0275811, 
                            .RightShank: 4.20669, 
                            .Head: -0.156357, 
                            .RightForearm: 1.08617, 
                            .LeftFoot: -0.896164, 
                            .RightUpperArm: 1.55604, 
                            .UpperBody: 0.0275792, 
                            .RightThigh: 1.18162, 
                            .LeftForearm: 5.21526], 
                        position: CGPoint(x: 1.5, y: -85.5)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .LeftThigh: 0.0, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.0, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 0.0, y: 0.0)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn)], 
            levelOfIntensity: 1,
            style: .HipHop,
            name: "Up & Down Double")
        
        _ = DanceMove(
            keyframes:
            [
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.095264,
                            .LeftShank: 1.28297,
                            .RightFoot: -5.14872,
                            .LeftThigh: -0.681851,
                            .LowerBody: 0.0,
                            .RightShank: 4.99787,
                            .Head: 0.0,
                            .RightForearm: 5.50436,
                            .LeftFoot: -0.887945,
                            .RightUpperArm: -0.131289,
                            .UpperBody: 0.0,
                            .RightThigh: 0.516256,
                            .LeftForearm: 1.58292],
                        position: CGPoint(x: 2.0, y: -31.5)),
                    angleCurve: .EaseInOut,
                    positionCurve: .EaseInOut),
                Keyframe(
                    time: 0.125,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: 3.9858,
                            .LeftShank: 0.0,
                            .RightFoot: -0.233113,
                            .LeftThigh: -0.552752,
                            .LowerBody: -0.0653828,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.523362,
                            .RightUpperArm: 1.99647,
                            .UpperBody: 0.0,
                            .RightThigh: 0.705749,
                            .LeftForearm: 0.0],
                        position: CGPoint(x: 82.0, y: 35.5)),
                    angleCurve: .EaseOut,
                    positionCurve: .EaseOut),
                Keyframe(
                    time: 0.25,
                    posture: Posture(
                        angles: [
                            .LeftUpperArm: -0.433809,
                            .LeftShank: 0.0,
                            .RightFoot: -0.233113,
                            .LeftThigh: -0.286618,
                            .LowerBody: -0.0653828,
                            .RightShank: 0.0,
                            .Head: 0.0,
                            .RightForearm: 0.0,
                            .LeftFoot: 0.375625,
                            .RightUpperArm: 0.316771,
                            .UpperBody: 0.0,
                            .RightThigh: 0.100543, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 188.0, y: 6.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.730636, 
                            .LeftShank: 0.437472, 
                            .RightFoot: -4.9333, 
                            .LeftThigh: 0.515445, 
                            .LowerBody: 0.521726, 
                            .RightShank: 4.38335, 
                            .Head: 0.0604664, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.220807, 
                            .RightUpperArm: 1.69183, 
                            .UpperBody: -0.451986, 
                            .RightThigh: 0.376607, 
                            .LeftForearm: 1.13314], 
                        position: CGPoint(x: 194.5, y: -57.0)), 
                    angleCurve: .EaseOut, 
                    positionCurve: .EaseOut), 
                Keyframe( 
                    time: 0.25, 
                    posture: Posture( 
                        angles: [
                            .LeftUpperArm: 0.0, 
                            .LeftShank: 0.0, 
                            .RightFoot: 0.0, 
                            .LeftThigh: 0.0, 
                            .LowerBody: 0.0, 
                            .RightShank: 0.0, 
                            .Head: 0.0, 
                            .RightForearm: 0.0, 
                            .LeftFoot: 0.0, 
                            .RightUpperArm: 0.0, 
                            .UpperBody: 0.0, 
                            .RightThigh: 0.0, 
                            .LeftForearm: 0.0], 
                        position: CGPoint(x: 187.5, y: 7.5)), 
                    angleCurve: .EaseIn, 
                    positionCurve: .EaseIn)], 
            levelOfIntensity: 2,
            style: .HipHop,
            name: "Hop And Down")


    }
    
}
