//
//  Moves.swift
//  AniDraw
//
//  Created by Mike on 7/6/16.
//  Copyright © 2016 yanjingzz. All rights reserved.
//

import Foundation

class MovesStorage {
    static let allMoves: [Int: [DanceMove]] =
        [1: [dance1_1, dance1_2, dance1_3, dance1_4, dance2_1, dance2_2, dance2_3, dance2_4, dance2_5]]
    
    static let dance1_1 = DanceMove(keyframes:
        [
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.78312,
                        .LeftShank: 0.0,
                        .RightFoot: 0.228166,
                        .LeftThigh: -0.508985,
                        .LowerBody: -0.0786719,
                        .RightShank: 0.0,
                        .Head: -0.00346017,
                        .RightForearm: 0.884818,
                        .LeftFoot: -0.178323,
                        .RightUpperArm: 0.303061,
                        .UpperBody: 0.444419,
                        .RightThigh: -0.457246,
                        .LeftForearm: 5.82682],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -0.618138,
                        .LeftShank: 0.0,
                        .RightFoot: -0.0982366,
                        .LeftThigh: -0.153417,
                        .LowerBody: 0.00724638,
                        .RightShank: 0.0,
                        .Head: -0.00346017,
                        .RightForearm: 0.631445,
                        .LeftFoot: -0.0375667,
                        .RightUpperArm: 2.18892,
                        .UpperBody: 0.117109,
                        .RightThigh: 0.0,
                        .LeftForearm: 0.0937462],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 4.32915,
                        .LeftShank: 0.0,
                        .RightFoot: 0.134648,
                        .LeftThigh: -0.0561199,
                        .LowerBody: 0.00724638,
                        .RightShank: 0.0,
                        .Head: -0.00346017,
                        .RightForearm: 0.837006,
                        .LeftFoot: -0.17863,
                        .RightUpperArm: 1.42179,
                        .UpperBody: 0.117109,
                        .RightThigh: -0.251466,
                        .LeftForearm: 5.61032],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 4.52747,
                        .LeftShank: 0.0,
                        .RightFoot: 0.139672,
                        .LeftThigh: -0.420276,
                        .LowerBody: -0.0124992,
                        .RightShank: 0.0,
                        .Head: -0.00346017,
                        .RightForearm: 2.27967,
                        .LeftFoot: 0.797793,
                        .RightUpperArm: 1.38051,
                        .UpperBody: 0.165149,
                        .RightThigh: -0.13411,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 4.55288,
                        .LeftShank: 0.0,
                        .RightFoot: -1.15296,
                        .LeftThigh: -0.14174,
                        .LowerBody: -0.0124992,
                        .RightShank: 5.35613,
                        .Head: -0.00346017,
                        .RightForearm: 0.0,
                        .LeftFoot: -0.0393773,
                        .RightUpperArm: 1.24302,
                        .UpperBody: 0.165149,
                        .RightThigh: 0.307573,
                        .LeftForearm: 4.08834],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -1.28726,
                        .LeftShank: 0.0,
                        .RightFoot: -6.52125,
                        .LeftThigh: -0.0497932,
                        .LowerBody: -0.0124992,
                        .RightShank: 5.30013,
                        .Head: -0.00346017,
                        .RightForearm: 4.60096,
                        .LeftFoot: 0.0275326,
                        .RightUpperArm: 0.327653,
                        .UpperBody: 0.165149,
                        .RightThigh: -0.565628,
                        .LeftForearm: 5.72226],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut)],
                             levelOfIntensity: 1)
    
    static let dance1_2 = DanceMove(keyframes:
        [
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.41182,
                        .LeftShank: 0.0,
                        .RightFoot: -0.0307913,
                        .LeftThigh: 0.0196396,
                        .LowerBody: -0.0263098,
                        .RightShank: 0.0,
                        .Head: 0.0513745,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.126612,
                        .RightUpperArm: -0.264802,
                        .UpperBody: 5.96046e-08,
                        .RightThigh: 0.0928068,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.69625,
                        .LeftShank: 0.0,
                        .RightFoot: -0.0733696,
                        .LeftThigh: 0.0615558,
                        .LowerBody: -0.0263098,
                        .RightShank: 0.0,
                        .Head: 0.0513745,
                        .RightForearm: 0.0,
                        .LeftFoot: -0.631559,
                        .RightUpperArm: 0.169757,
                        .UpperBody: 5.96046e-08,
                        .RightThigh: 0.0385892,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.46789,
                        .LeftShank: 0.0,
                        .RightFoot: -5.93383,
                        .LeftThigh: 0.0734728,
                        .LowerBody: -0.00999957,
                        .RightShank: 5.43837,
                        .Head: 0.00687367,
                        .RightForearm: 5.70701,
                        .LeftFoot: -0.474901,
                        .RightUpperArm: 2.61429,
                        .UpperBody: 0.358771,
                        .RightThigh: -0.582372,
                        .LeftForearm: 0.570054],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -1.30808,
                        .LeftShank: 0.0,
                        .RightFoot: -5.69017,
                        .LeftThigh: -0.199714,
                        .LowerBody: -0.00999957,
                        .RightShank: 5.43837,
                        .Head: 0.00687367,
                        .RightForearm: 0.0,
                        .LeftFoot: -0.179819,
                        .RightUpperArm: 2.10372,
                        .UpperBody: 0.358771,
                        .RightThigh: -0.473246,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 4.22623,
                        .LeftShank: 0.0,
                        .RightFoot: 0.132933,
                        .LeftThigh: 0.0196396,
                        .LowerBody: -0.0263098,
                        .RightShank: 4.25332,
                        .Head: 0.0116559,
                        .RightForearm: 1.21788,
                        .LeftFoot: 1.1815,
                        .RightUpperArm: 1.83454,
                        .UpperBody: 5.96046e-08,
                        .RightThigh: 0.0715664,
                        .LeftForearm: 5.07431],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -1.82182,
                        .LeftShank: 0.0,
                        .RightFoot: 0.132933,
                        .LeftThigh: 0.0196396,
                        .LowerBody: -0.0263098,
                        .RightShank: -2.02987,
                        .Head: 0.0514562,
                        .RightForearm: 4.73224,
                        .LeftFoot: 1.1815,
                        .RightUpperArm: 1.56079,
                        .UpperBody: 5.96046e-08,
                        .RightThigh: 0.0715664,
                        .LeftForearm: 1.82645],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -0.984167,
                        .LeftShank: 0.0,
                        .RightFoot: -0.0117909,
                        .LeftThigh: 0.0196396,
                        .LowerBody: -5.96046e-08,
                        .RightShank: 0.0,
                        .Head: 0.0111517,
                        .RightForearm: 0.0,
                        .LeftFoot: -0.016847,
                        .RightUpperArm: 1.16895,
                        .UpperBody: 5.96046e-08,
                        .RightThigh: -0.0375319,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut)],
                             levelOfIntensity: 1)
    
    static let dance1_3 = DanceMove(keyframes:
        [
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 4.58275,
                        .LeftShank: -0.907629,
                        .RightFoot: -0.88852,
                        .LeftThigh: 0.358762,
                        .LowerBody: 6.2928,
                        .RightShank: -1.83458,
                        .Head: 0.0190668,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.914935,
                        .RightUpperArm: 2.46597,
                        .UpperBody: -4.01975,
                        .RightThigh: 1.01704,
                        .LeftForearm: 4.93576],
                    position: CGPoint(x: -21.0, y: -26.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.57269,
                        .LeftShank: -0.907629,
                        .RightFoot: -0.88852,
                        .LeftThigh: 0.358762,
                        .LowerBody: 6.33667,
                        .RightShank: -1.83458,
                        .Head: -0.00823402,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.914935,
                        .RightUpperArm: 2.46597,
                        .UpperBody: -2.99203,
                        .RightThigh: 1.01704,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -21.0, y: -26.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.57269,
                        .LeftShank: -0.907629,
                        .RightFoot: 4.5841,
                        .LeftThigh: 0.358762,
                        .LowerBody: 6.22511,
                        .RightShank: 0.0,
                        .Head: -0.18853,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.914935,
                        .RightUpperArm: 2.07195,
                        .UpperBody: -3.03094,
                        .RightThigh: -7.09956,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -21.0, y: -26.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 4.26022,
                        .LeftShank: 0.0,
                        .RightFoot: 4.5841,
                        .LeftThigh: -4.78103,
                        .LowerBody: 6.2988,
                        .RightShank: 0.0,
                        .Head: -0.00823402,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.875963,
                        .RightUpperArm: 7.01642,
                        .UpperBody: -4.01565,
                        .RightThigh: -4.39498,
                        .LeftForearm: 5.43621],
                    position: CGPoint(x: -21.0, y: -26.0)),
                angleCurve: .EaseIn,
                positionCurve: .None),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.91,
                        .LeftShank: 0.0,
                        .RightFoot: -0.63363,
                        .LeftThigh: -4.78103,
                        .LowerBody: 6.27594,
                        .RightShank: 0.0,
                        .Head: -0.00823402,
                        .RightForearm: 0.843743,
                        .LeftFoot: 0.875963,
                        .RightUpperArm: 0.370606,
                        .UpperBody: -1.91009,
                        .RightThigh: -4.2651,
                        .LeftForearm: 1.18088],
                    position: CGPoint(x: -21.0, y: -26.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 5.12573,
                        .LeftShank: 0.0,
                        .RightFoot: -0.63363,
                        .LeftThigh: -4.78103,
                        .LowerBody: -0.0313991,
                        .RightShank: 0.0,
                        .Head: 0.0846745,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.875963,
                        .RightUpperArm: 1.12715,
                        .UpperBody: -0.96007,
                        .RightThigh: -4.2651,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -21.0, y: -26.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 5.12573,
                        .LeftShank: 0.0,
                        .RightFoot: 0.208723,
                        .LeftThigh: 0.0310863,
                        .LowerBody: 0.0,
                        .RightShank: 0.0,
                        .Head: -0.0410724,
                        .RightForearm: 0.0,
                        .LeftFoot: -0.206277,
                        .RightUpperArm: 1.12715,
                        .UpperBody: 0.0,
                        .RightThigh: 0.133411,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -21.0, y: -26.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut)],
                             levelOfIntensity: 1)
    
    static let dance1_4 = DanceMove(keyframes:
        [
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -0.690093,
                        .LeftShank: 0.0,
                        .RightFoot: 0.0,
                        .LeftThigh: -0.0241944,
                        .LowerBody: 0.0135127,
                        .RightShank: 0.0,
                        .Head: 0.0406884,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.0,
                        .RightUpperArm: 0.545557,
                        .UpperBody: -0.0135127,
                        .RightThigh: 0.205996,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -0.690093,
                        .LeftShank: 1.00178,
                        .RightFoot: -0.74718,
                        .LeftThigh: -0.68897,
                        .LowerBody: -0.0187428,
                        .RightShank: 0.0,
                        .Head: -0.0436226,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.867527,
                        .RightUpperArm: 0.525649,
                        .UpperBody: -0.257771,
                        .RightThigh: 0.388911,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -23.5, y: 87.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.70621,
                        .LeftShank: 0.999572,
                        .RightFoot: 0.991596,
                        .LeftThigh: -0.687506,
                        .LowerBody: -0.0186718,
                        .RightShank: 0.0,
                        .Head: -0.043437,
                        .RightForearm: 0.0,
                        .LeftFoot: -1.2273,
                        .RightUpperArm: 2.28768,
                        .UpperBody: -0.257233,
                        .RightThigh: 1.46831,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -23.4483, y: 86.8085)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -2.57282,
                        .LeftShank: 0.999577,
                        .RightFoot: -1.03172,
                        .LeftThigh: -0.0473258,
                        .LowerBody: -0.018672,
                        .RightShank: 0.0,
                        .Head: -0.0434374,
                        .RightForearm: 0.0,
                        .LeftFoot: -0.531715,
                        .RightUpperArm: 2.2838,
                        .UpperBody: -0.257235,
                        .RightThigh: 1.46593,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -13.9483, y: 4.30869)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.71037,
                        .LeftShank: 0.0,
                        .RightFoot: 0.637432,
                        .LeftThigh: -0.173732,
                        .LowerBody: -0.00259197,
                        .RightShank: 0.0,
                        .Head: 0.0340644,
                        .RightForearm: 0.0,
                        .LeftFoot: -0.452414,
                        .RightUpperArm: 2.2838,
                        .UpperBody: 0.00137079,
                        .RightThigh: 0.252353,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -13.9483, y: 4.30872)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -2.57282,
                        .LeftShank: 0.00211483,
                        .RightFoot: -0.795909,
                        .LeftThigh: -0.173465,
                        .LowerBody: 0.0200706,
                        .RightShank: 0.0,
                        .Head: 0.0339004,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.710744,
                        .RightUpperArm: 2.2838,
                        .UpperBody: 0.000823647,
                        .RightThigh: 0.25492,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 23.5516, y: 65.3087)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -0.710762,
                        .LeftShank: 0.0,
                        .RightFoot: -0.0311424,
                        .LeftThigh: -0.0547908,
                        .LowerBody: -0.00813818,
                        .RightShank: 0.0,
                        .Head: 0.0339008,
                        .RightForearm: 5.22681,
                        .LeftFoot: 0.149207,
                        .RightUpperArm: 0.419688,
                        .UpperBody: 0.0479978,
                        .RightThigh: -0.0471059,
                        .LeftForearm: 1.09076],
                    position: CGPoint(x: 17.4799, y: 38.1919)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut)],
                             levelOfIntensity: 1)
    
    static let dance2_1 = DanceMove(keyframes:
    [
    Keyframe(
    time: 0.5,
    posture: Posture(
    angles: [
    .LeftUpperArm: 4.36973,
    .LeftShank: 0.0,
    .RightFoot: -0.722888,
    .LeftThigh: 0.530275,
    .LowerBody: 0.296956,
    .RightShank: 0.0,
    .Head: -0.0393565,
    .RightForearm: 0.0,
    .LeftFoot: -0.158864,
    .RightUpperArm: 2.47712,
    .UpperBody: -0.198293,
    .RightThigh: -0.24266,
    .LeftForearm: 2.1822],
    position: CGPoint(x: 12.6453, y: 18.3278)),
    angleCurve: .EaseInOut,
    positionCurve: .EaseInOut),
    Keyframe(
    time: 0.5,
    posture: Posture(
    angles: [
    .LeftUpperArm: -0.773683,
    .LeftShank: 0.0,
    .RightFoot: -0.709149,
    .LeftThigh: 0.147389,
    .LowerBody: -0.317401,
    .RightShank: 0.0,
    .Head: -0.0225049,
    .RightForearm: 0.0,
    .LeftFoot: -0.128508,
    .RightUpperArm: 2.30993,
    .UpperBody: 0.418066,
    .RightThigh: -0.638334,
    .LeftForearm: 0.0],
    position: CGPoint(x: 12.9019, y: 18.6996)),
    angleCurve: .EaseInOut,
    positionCurve: .EaseInOut),
    Keyframe(
    time: 0.5,
    posture: Posture(
    angles: [
    .LeftUpperArm: 3.93345,
    .LeftShank: 0.0,
    .RightFoot: -1.3528,
    .LeftThigh: -0.322909,
    .LowerBody: -0.00586289,
    .RightShank: 0.0,
    .Head: 0.0490492,
    .RightForearm: 0.0,
    .LeftFoot: 0.722012,
    .RightUpperArm: 2.26978,
    .UpperBody: -0.0163068,
    .RightThigh: 2.23886,
    .LeftForearm: 0.0],
    position: CGPoint(x: 12.9025, y: 18.7004)),
    angleCurve: .EaseInOut,
    positionCurve: .EaseInOut),
    Keyframe(
    time: 0.5,
    posture: Posture(
    angles: [
    .LeftUpperArm: 3.73323,
    .LeftShank: 0.0,
    .RightFoot: -0.495629,
    .LeftThigh: 0.0222147,
    .LowerBody: -0.00586289,
    .RightShank: 0.0,
    .Head: 0.0490492,
    .RightForearm: 0.0,
    .LeftFoot: 0.755389,
    .RightUpperArm: 2.51073,
    .UpperBody: -0.0163068,
    .RightThigh: 1.84866,
    .LeftForearm: 0.509248],
    position: CGPoint(x: 11.4025, y: 56.7004)),
    angleCurve: .EaseInOut,
    positionCurve: .EaseInOut),
    Keyframe(
    time: 0.5,
    posture: Posture(
    angles: [
    .LeftUpperArm: 3.45239,
    .LeftShank: 0.0,
    .RightFoot: -0.77136,
    .LeftThigh: 0.0222147,
    .LowerBody: -0.00586289,
    .RightShank: 0.0,
    .Head: 0.0490492,
    .RightForearm: 0.0,
    .LeftFoot: 0.840576,
    .RightUpperArm: 3.00189,
    .UpperBody: -0.0163068,
    .RightThigh: 1.62137,
    .LeftForearm: 0.0],
    position: CGPoint(x: 11.4025, y: 56.7004)),
    angleCurve: .EaseInOut,
    positionCurve: .EaseInOut),
    Keyframe(
    time: 0.5,
    posture: Posture(
    angles: [
    .LeftUpperArm: 3.58921,
    .LeftShank: 0.0,
    .RightFoot: -0.855163,
    .LeftThigh: -0.0327239,
    .LowerBody: 0.00994492,
    .RightShank: 0.0,
    .Head: 0.0275756,
    .RightForearm: 0.0,
    .LeftFoot: 0.89344,
    .RightUpperArm: 2.55656,
    .UpperBody: 0.0907247,
    .RightThigh: -0.198045,
    .LeftForearm: 0.0],
    position: CGPoint(x: 14.9025, y: 40.2004)),
    angleCurve: .EaseInOut,
    positionCurve: .EaseInOut),
    Keyframe(
    time: 0.5,
    posture: Posture(
    angles: [
    .LeftUpperArm: -0.788417,
    .LeftShank: 0.0,
    .RightFoot: -0.048409,
    .LeftThigh: -0.0262787,
    .LowerBody: -0.00522051,
    .RightShank: 0.0,
    .Head: 0.0275756,
    .RightForearm: 5.25795,
    .LeftFoot: 0.114341,
    .RightUpperArm: 0.583536,
    .UpperBody: 0.0907247,
    .RightThigh: -0.199755,
    .LeftForearm: 1.19513],
    position: CGPoint(x: 14.8848, y: 40.011)),
    angleCurve: .EaseInOut,
    positionCurve: .EaseInOut)],
    levelOfIntensity: 1)
    
    static let dance2_2 = DanceMove(keyframes:
        [
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -1.19612,
                        .LeftShank: 0.0,
                        .RightFoot: -0.966667,
                        .LeftThigh: -1.2238,
                        .LowerBody: -0.198646,
                        .RightShank: 0.0,
                        .Head: 0.157226,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.686549,
                        .RightUpperArm: 2.65058,
                        .UpperBody: -0.350728,
                        .RightThigh: 0.504737,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -1.19612,
                        .LeftShank: 0.0,
                        .RightFoot: -0.966667,
                        .LeftThigh: -1.2238,
                        .LowerBody: -0.833759,
                        .RightShank: 0.0,
                        .Head: 0.157226,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.686549,
                        .RightUpperArm: 2.65058,
                        .UpperBody: 0.284385,
                        .RightThigh: 0.504737,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -0.161829,
                        .LeftShank: 0.0,
                        .RightFoot: -0.966667,
                        .LeftThigh: -1.2238,
                        .LowerBody: -0.833759,
                        .RightShank: 0.0,
                        .Head: 0.157226,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.0311953,
                        .RightUpperArm: 2.65058,
                        .UpperBody: 0.284385,
                        .RightThigh: 0.504737,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.40025,
                        .LeftShank: 0.0,
                        .RightFoot: -0.542102,
                        .LeftThigh: 4.67736,
                        .LowerBody: 0.00570226,
                        .RightShank: 0.0,
                        .Head: -0.0912468,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.586285,
                        .RightUpperArm: 2.87134,
                        .UpperBody: 0.284385,
                        .RightThigh: 1.63151,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 0.0, y: 0.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.40025,
                        .LeftShank: 0.0,
                        .RightFoot: -0.542102,
                        .LeftThigh: -0.80569,
                        .LowerBody: 0.00570226,
                        .RightShank: 0.0,
                        .Head: -0.0912468,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.586285,
                        .RightUpperArm: 2.0986,
                        .UpperBody: 0.284385,
                        .RightThigh: 1.63151,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: 1.5, y: 50.5)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.69373,
                        .LeftShank: 0.0,
                        .RightFoot: -0.542102,
                        .LeftThigh: -0.273211,
                        .LowerBody: -0.00608504,
                        .RightShank: 0.0,
                        .Head: -0.0912468,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.824496,
                        .RightUpperArm: 1.31525,
                        .UpperBody: 0.284385,
                        .RightThigh: 1.75217,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -78.5, y: 118.0)),
                angleCurve: .EaseIn,
                positionCurve: .EaseIn),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.69373,
                        .LeftShank: 0.0,
                        .RightFoot: -0.247026,
                        .LeftThigh: -0.273211,
                        .LowerBody: -0.00608504,
                        .RightShank: 4.39137,
                        .Head: -0.0912468,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.824496,
                        .RightUpperArm: 1.31525,
                        .UpperBody: 0.284385,
                        .RightThigh: 0.733764,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -47.5, y: 75.0)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: 3.27326,
                        .LeftShank: 0.0,
                        .RightFoot: -0.630671,
                        .LeftThigh: -0.807824,
                        .LowerBody: 0.00570226,
                        .RightShank: 0.0,
                        .Head: -0.0912468,
                        .RightForearm: 0.0,
                        .LeftFoot: 1.1904,
                        .RightUpperArm: 1.31525,
                        .UpperBody: 0.284385,
                        .RightThigh: -0.345202,
                        .LeftForearm: 0.0],
                    position: CGPoint(x: -55.0, y: 54.5)),
                angleCurve: .EaseInOut,
                positionCurve: .EaseInOut),
            Keyframe(
                time: 0.5,
                posture: Posture(
                    angles: [
                        .LeftUpperArm: -0.45608,
                        .LeftShank: 0.0,
                        .RightFoot: -0.630671,
                        .LeftThigh: -0.0348283,
                        .LowerBody: -0.020684,
                        .RightShank: 0.0,
                        .Head: -0.00819147,
                        .RightForearm: 0.0,
                        .LeftFoot: 0.563406,
                        .RightUpperArm: 0.263373,
                        .UpperBody: 0.0777649, 
                        .RightThigh: -0.0613948, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -55.0, y: 54.5)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut)], 
                             levelOfIntensity: 1)
    
    static let dance2_3 = DanceMove(keyframes:  
        [
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.46564, 
                        .LeftShank: 0.0, 
                        .RightFoot: -1.04853, 
                        .LeftThigh: 0.357753, 
                        .LowerBody: -0.0340058, 
                        .RightShank: 0.0, 
                        .Head: -0.0675434, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.383981, 
                        .RightUpperArm: 2.18775, 
                        .UpperBody: 0.0880073, 
                        .RightThigh: -0.18047, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: -1.52955, 
                        .LeftShank: 0.0, 
                        .RightFoot: -1.04853, 
                        .LeftThigh: 0.0958173, 
                        .LowerBody: -0.0340058, 
                        .RightShank: 0.0, 
                        .Head: -0.0675434, 
                        .RightForearm: 1.36451, 
                        .LeftFoot: 1.07728, 
                        .RightUpperArm: 1.23077, 
                        .UpperBody: 0.0880073, 
                        .RightThigh: -0.18047, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 4.75077, 
                        .LeftShank: 0.0, 
                        .RightFoot: -1.04853, 
                        .LeftThigh: 0.0502654, 
                        .LowerBody: -0.0340058, 
                        .RightShank: 0.0, 
                        .Head: -0.0675434, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.717573, 
                        .RightUpperArm: 2.02797, 
                        .UpperBody: 0.0880073, 
                        .RightThigh: 1.98101, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.5973, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.612152, 
                        .LeftThigh: -0.0650642, 
                        .LowerBody: 0.0419922, 
                        .RightShank: 0.0, 
                        .Head: -0.0365098, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.717573, 
                        .RightUpperArm: 2.46326, 
                        .UpperBody: 0.110657, 
                        .RightThigh: 2.52416, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: -1.48754, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.977011, 
                        .LeftThigh: -0.0650642, 
                        .LowerBody: 0.0419922, 
                        .RightShank: 0.0, 
                        .Head: 0.0424993, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.717573, 
                        .RightUpperArm: 2.2369, 
                        .UpperBody: 0.110657, 
                        .RightThigh: 1.42952, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 5.30193, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.842332, 
                        .LeftThigh: -1.37788, 
                        .LowerBody: 6.24902, 
                        .RightShank: 0.0, 
                        .Head: 0.0424993, 
                        .RightForearm: 0.0, 
                        .LeftFoot: -0.0297143, 
                        .RightUpperArm: 2.68168, 
                        .UpperBody: -1.87592, 
                        .RightThigh: -4.33473, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -24.5, y: -11.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 5.30193, 
                        .LeftShank: 1.54982, 
                        .RightFoot: -0.820717, 
                        .LeftThigh: -0.389659, 
                        .LowerBody: -0.108704, 
                        .RightShank: 0.0, 
                        .Head: 0.0117745, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.966278, 
                        .RightUpperArm: 0.662649, 
                        .UpperBody: -0.71465, 
                        .RightThigh: 0.786815, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -24.5, y: -11.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: -0.584186, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.906479, 
                        .LeftThigh: -0.1134, 
                        .LowerBody: -0.0338249, 
                        .RightShank: 0.0, 
                        .Head: -0.00192499, 
                        .RightForearm: 5.69857, 
                        .LeftFoot: 0.966278, 
                        .RightUpperArm: 0.402916, 
                        .UpperBody: 0.0713074, 
                        .RightThigh: 0.000100613, 
                        .LeftForearm: 0.577727], 
                    position: CGPoint(x: -24.5, y: -11.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut)], 
                             levelOfIntensity: 1)
    
    static let dance2_4 = DanceMove(keyframes:  
        [
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 0.97423, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.945122, 
                        .LeftThigh: -0.121379, 
                        .LowerBody: -0.021294, 
                        .RightShank: 0.0, 
                        .Head: 0.0974797, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.797952, 
                        .RightUpperArm: -1.24446, 
                        .UpperBody: 0.15595, 
                        .RightThigh: -0.196719, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -51.3857, y: 57.3723)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 5.1217, 
                        .LeftShank: 1.88091, 
                        .RightFoot: -1.39809, 
                        .LeftThigh: -1.08749, 
                        .LowerBody: -0.0114594, 
                        .RightShank: 1.43318, 
                        .Head: -0.00667751, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.451019, 
                        .RightUpperArm: 3.79477, 
                        .UpperBody: -0.469428, 
                        .RightThigh: 1.18085, 
                        .LeftForearm: 4.58138], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 1.73968, 
                        .LeftShank: 1.98903, 
                        .RightFoot: -0.841142, 
                        .LeftThigh: -0.863789, 
                        .LowerBody: 0.161697, 
                        .RightShank: 0.0, 
                        .Head: -0.00667751, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.79729, 
                        .RightUpperArm: 1.43212, 
                        .UpperBody: -0.483447, 
                        .RightThigh: 0.709391, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -51.5, y: 57.5)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 5.17036, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.842378, 
                        .LeftThigh: -1.40965, 
                        .LowerBody: -0.336514, 
                        .RightShank: 0.0, 
                        .Head: -0.00834692, 
                        .RightForearm: 0.0, 
                        .LeftFoot: -0.155676, 
                        .RightUpperArm: 2.53879, 
                        .UpperBody: 0.0144103, 
                        .RightThigh: 0.314909, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -51.3857, y: 57.3723)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 5.17036, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.842378, 
                        .LeftThigh: 0.154491, 
                        .LowerBody: -0.0499746, 
                        .RightShank: 0.0, 
                        .Head: -0.00834692, 
                        .RightForearm: 0.0, 
                        .LeftFoot: -0.055426, 
                        .RightUpperArm: 4.5426, 
                        .UpperBody: 0.0144103, 
                        .RightThigh: 1.85545, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -51.3857, y: 57.3723)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 4.02946, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.842378, 
                        .LeftThigh: 0.252443, 
                        .LowerBody: -0.0678046, 
                        .RightShank: 1.04324, 
                        .Head: 0.0188522, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.94479, 
                        .RightUpperArm: 6.90295, 
                        .UpperBody: -0.0483658, 
                        .RightThigh: 1.54146, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -51.3857, y: 57.3723)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 0.292237, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.901286, 
                        .LeftThigh: -0.117733, 
                        .LowerBody: 0.0297225, 
                        .RightShank: 0.0, 
                        .Head: -0.00834692, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.895462, 
                        .RightUpperArm: -0.636115, 
                        .UpperBody: 0.102934, 
                        .RightThigh: -0.228519, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -51.3857, y: 57.3723)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: -0.804078, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.354146, 
                        .LeftThigh: 6.16545, 
                        .LowerBody: 0.0297213, 
                        .RightShank: 0.0, 
                        .Head: -0.00834692, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.207871, 
                        .RightUpperArm: 0.509488, 
                        .UpperBody: 0.102934, 
                        .RightThigh: -0.228518, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: -51.3857, y: 57.3723)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut)], 
                             levelOfIntensity: 1)
    
    static let dance2_5 = DanceMove(keyframes:  
        [
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.5937, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.976056, 
                        .LeftThigh: -0.105537, 
                        .LowerBody: -0.00238657, 
                        .RightShank: 0.0, 
                        .Head: -0.00532401, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.89758, 
                        .RightUpperArm: 2.47852, 
                        .UpperBody: 0.110657, 
                        .RightThigh: -0.151758, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.51084, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.62059, 
                        .LeftThigh: -0.105305, 
                        .LowerBody: -0.00678933, 
                        .RightShank: 0.0, 
                        .Head: -0.00531227, 
                        .RightForearm: 0.597079, 
                        .LeftFoot: 0.852587, 
                        .RightUpperArm: 2.47034, 
                        .UpperBody: 0.0798299, 
                        .RightThigh: 0.355175, 
                        .LeftForearm: 5.90922], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.51102, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.621379, 
                        .LeftThigh: 0.0948508, 
                        .LowerBody: -0.00677955, 
                        .RightShank: 0.0, 
                        .Head: -0.00531229, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.916402, 
                        .RightUpperArm: 2.11461, 
                        .UpperBody: 0.0798984, 
                        .RightThigh: 2.10105, 
                        .LeftForearm: -0.373138], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseIn, 
                positionCurve: .Linear), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.47908, 
                        .LeftShank: 0.0, 
                        .RightFoot: -0.621379, 
                        .LeftThigh: -0.0956045, 
                        .LowerBody: -0.00677955, 
                        .RightShank: 0.0, 
                        .Head: -0.00531229, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.916402, 
                        .RightUpperArm: 1.66087, 
                        .UpperBody: 0.0798984, 
                        .RightThigh: 2.83941, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseOut, 
                positionCurve: .EaseOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.47912, 
                        .LeftShank: 0.0, 
                        .RightFoot: -1.02507, 
                        .LeftThigh: -5.87454, 
                        .LowerBody: 6.18599, 
                        .RightShank: 0.0, 
                        .Head: -0.0218158, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.916402, 
                        .RightUpperArm: 1.99068, 
                        .UpperBody: -1.77948, 
                        .RightThigh: -4.36024, 
                        .LeftForearm: -0.00037086], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseOut, 
                positionCurve: .EaseOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.51981, 
                        .LeftShank: 0.0, 
                        .RightFoot: 5.4932, 
                        .LeftThigh: -7.60338, 
                        .LowerBody: 6.27234, 
                        .RightShank: 0.0, 
                        .Head: -0.0218158, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.426419, 
                        .RightUpperArm: 6.76369, 
                        .UpperBody: -4.51036, 
                        .RightThigh: -6.46726, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseOut, 
                positionCurve: .EaseOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.51981, 
                        .LeftShank: 1.52542, 
                        .RightFoot: -0.898791, 
                        .LeftThigh: -0.968602, 
                        .LowerBody: 0.0485842, 
                        .RightShank: 0.0, 
                        .Head: -0.0218158, 
                        .RightForearm: 0.0, 
                        .LeftFoot: 0.426419, 
                        .RightUpperArm: 6.76369, 
                        .UpperBody: 0.0227233, 
                        .RightThigh: -0.208408, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut), 
            Keyframe( 
                time: 0.5, 
                posture: Posture( 
                    angles: [
                        .LeftUpperArm: 3.51981, 
                        .LeftShank: 1.52542, 
                        .RightFoot: -0.898791, 
                        .LeftThigh: 0.0720502, 
                        .LowerBody: 0.0485842, 
                        .RightShank: 0.0, 
                        .Head: -0.0218158, 
                        .RightForearm: 0.0, 
                        .LeftFoot: -0.724789, 
                        .RightUpperArm: 6.76369, 
                        .UpperBody: 0.0227233, 
                        .RightThigh: -0.208408, 
                        .LeftForearm: 0.0], 
                    position: CGPoint(x: 0.0, y: 0.0)), 
                angleCurve: .EaseInOut, 
                positionCurve: .EaseInOut)],
                             levelOfIntensity: 1)
    
    
}